// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class AuthInfo;
@class AuthInfoBuilder;
@class ContactSessionInfo;
@class ContactSessionInfoBuilder;
@class DepartInfo;
@class DepartInfoBuilder;
@class GroupInfo;
@class GroupInfoBuilder;
@class GroupVersionInfo;
@class GroupVersionInfoBuilder;
@class IpAddr;
@class IpAddrBuilder;
@class MsgInfo;
@class MsgInfoBuilder;
@class OfflineFileInfo;
@class OfflineFileInfoBuilder;
@class PushResult;
@class PushResultBuilder;
@class ServerUserStat;
@class ServerUserStatBuilder;
@class ShieldStatus;
@class ShieldStatusBuilder;
@class UnreadInfo;
@class UnreadInfoBuilder;
@class UserInfo;
@class UserInfoBuilder;
@class UserStat;
@class UserStatBuilder;
@class UserTokenInfo;
@class UserTokenInfoBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif

typedef enum {
  ServiceIDSidLogin = 1,
  ServiceIDSidBuddyList = 2,
  ServiceIDSidMsg = 3,
  ServiceIDSidGroup = 4,
  ServiceIDSidFile = 5,
  ServiceIDSidSwitchService = 6,
  ServiceIDSidOther = 7,
  ServiceIDSidInternal = 8,
} ServiceID;

BOOL ServiceIDIsValidValue(ServiceID value);

typedef enum {
  LoginCmdIDCidLoginReqMsgserver = 257,
  LoginCmdIDCidLoginResMsgserver = 258,
  LoginCmdIDCidLoginReqUserlogin = 259,
  LoginCmdIDCidLoginResUserlogin = 260,
  LoginCmdIDCidLoginReqLoginout = 261,
  LoginCmdIDCidLoginResLoginout = 262,
  LoginCmdIDCidLoginKickUser = 263,
  LoginCmdIDCidLoginReqDevicetoken = 264,
  LoginCmdIDCidLoginResDevicetoken = 265,
  LoginCmdIDCidLoginReqKickpcclient = 266,
  LoginCmdIDCidLoginResKickpcclient = 267,
} LoginCmdID;

BOOL LoginCmdIDIsValidValue(LoginCmdID value);

typedef enum {
  BuddyListCmdIDCidBuddyListRecentContactSessionRequest = 513,
  BuddyListCmdIDCidBuddyListRecentContactSessionResponse = 514,
  BuddyListCmdIDCidBuddyListStatusNotify = 515,
  BuddyListCmdIDCidBuddyListUserInfoRequest = 516,
  BuddyListCmdIDCidBuddyListUserInfoResponse = 517,
  BuddyListCmdIDCidBuddyListRemoveSessionReq = 518,
  BuddyListCmdIDCidBuddyListRemoveSessionRes = 519,
  BuddyListCmdIDCidBuddyListAllUserRequest = 520,
  BuddyListCmdIDCidBuddyListAllUserResponse = 521,
  BuddyListCmdIDCidBuddyListUsersStatusRequest = 522,
  BuddyListCmdIDCidBuddyListUsersStatusResponse = 523,
  BuddyListCmdIDCidBuddyListChangeAvatarRequest = 524,
  BuddyListCmdIDCidBuddyListChangeAvatarResponse = 525,
  BuddyListCmdIDCidBuddyListPcLoginStatusNotify = 526,
  BuddyListCmdIDCidBuddyListRemoveSessionNotify = 527,
  BuddyListCmdIDCidBuddyListDepartmentRequest = 528,
  BuddyListCmdIDCidBuddyListDepartmentResponse = 529,
} BuddyListCmdID;

BOOL BuddyListCmdIDIsValidValue(BuddyListCmdID value);

typedef enum {
  MessageCmdIDCidMsgData = 769,
  MessageCmdIDCidMsgDataAck = 770,
  MessageCmdIDCidMsgReadAck = 771,
  MessageCmdIDCidMsgReadNotify = 772,
  MessageCmdIDCidMsgTimeRequest = 773,
  MessageCmdIDCidMsgTimeResponse = 774,
  MessageCmdIDCidMsgUnreadCntRequest = 775,
  MessageCmdIDCidMsgUnreadCntResponse = 776,
  MessageCmdIDCidMsgListRequest = 777,
  MessageCmdIDCidMsgListResponse = 778,
  MessageCmdIDCidMsgGetLatestMsgIdReq = 779,
  MessageCmdIDCidMsgGetLatestMsgIdRsp = 780,
  MessageCmdIDCidMsgGetByMsgIdReq = 781,
  MessageCmdIDCidMsgGetByMsgIdRes = 782,
} MessageCmdID;

BOOL MessageCmdIDIsValidValue(MessageCmdID value);

typedef enum {
  GroupCmdIDCidGroupNormalListRequest = 1025,
  GroupCmdIDCidGroupNormalListResponse = 1026,
  GroupCmdIDCidGroupInfoRequest = 1027,
  GroupCmdIDCidGroupInfoResponse = 1028,
  GroupCmdIDCidGroupCreateRequest = 1029,
  GroupCmdIDCidGroupCreateResponse = 1030,
  GroupCmdIDCidGroupChangeMemberRequest = 1031,
  GroupCmdIDCidGroupChangeMemberResponse = 1032,
  GroupCmdIDCidGroupShieldGroupRequest = 1033,
  GroupCmdIDCidGroupShieldGroupResponse = 1034,
  GroupCmdIDCidGroupChangeMemberNotify = 1035,
} GroupCmdID;

BOOL GroupCmdIDIsValidValue(GroupCmdID value);

typedef enum {
  FileCmdIDCidFileLoginReq = 1281,
  FileCmdIDCidFileLoginRes = 1282,
  FileCmdIDCidFileState = 1283,
  FileCmdIDCidFilePullDataReq = 1284,
  FileCmdIDCidFilePullDataRsp = 1285,
  FileCmdIDCidFileRequest = 1286,
  FileCmdIDCidFileResponse = 1287,
  FileCmdIDCidFileNotify = 1288,
  FileCmdIDCidFileHasOfflineReq = 1289,
  FileCmdIDCidFileHasOfflineRes = 1290,
  FileCmdIDCidFileAddOfflineReq = 1291,
  FileCmdIDCidFileDelOfflineReq = 1292,
} FileCmdID;

BOOL FileCmdIDIsValidValue(FileCmdID value);

typedef enum {
  SwitchServiceCmdIDCidSwitchP2PCmd = 1537,
} SwitchServiceCmdID;

BOOL SwitchServiceCmdIDIsValidValue(SwitchServiceCmdID value);

typedef enum {
  OtherCmdIDCidOtherHeartbeat = 1793,
  OtherCmdIDCidOtherStopRecvPacket = 1794,
  OtherCmdIDCidOtherValidateReq = 1795,
  OtherCmdIDCidOtherValidateRsp = 1796,
  OtherCmdIDCidOtherGetDeviceTokenReq = 1797,
  OtherCmdIDCidOtherGetDeviceTokenRsp = 1798,
  OtherCmdIDCidOtherRoleSet = 1799,
  OtherCmdIDCidOtherOnlineUserInfo = 1800,
  OtherCmdIDCidOtherMsgServInfo = 1801,
  OtherCmdIDCidOtherUserStatusUpdate = 1802,
  OtherCmdIDCidOtherUserCntUpdate = 1803,
  OtherCmdIDCidOtherServerKickUser = 1805,
  OtherCmdIDCidOtherLoginStatusNotify = 1806,
  OtherCmdIDCidOtherPushToUserReq = 1807,
  OtherCmdIDCidOtherPushToUserRsp = 1808,
  OtherCmdIDCidOtherGetShieldReq = 1809,
  OtherCmdIDCidOtherGetShieldRsp = 1810,
  OtherCmdIDCidOtherFileTransferReq = 1841,
  OtherCmdIDCidOtherFileTransferRsp = 1842,
  OtherCmdIDCidOtherFileServerIpReq = 1843,
  OtherCmdIDCidOtherFileServerIpRsp = 1844,
} OtherCmdID;

BOOL OtherCmdIDIsValidValue(OtherCmdID value);

typedef enum {
  InternalCmdIDCidInternalSyncAuthInfoReq = 2049,
  InternalCmdIDCidInternalSyncAuthInfoRsp = 2050,
  InternalCmdIDCidInternalUserIdByNickNameReq = 2051,
  InternalCmdIDCidInternalUserIdByNickNameRsp = 2052,
} InternalCmdID;

BOOL InternalCmdIDIsValidValue(InternalCmdID value);

typedef enum {
  ResultTypeRefuseReasonNone = 0,
  ResultTypeRefuseReasonNoMsgServer = 1,
  ResultTypeRefuseReasonMsgServerFull = 2,
  ResultTypeRefuseReasonNoDbServer = 3,
  ResultTypeRefuseReasonNoLoginServer = 4,
  ResultTypeRefuseReasonNoRouteServer = 5,
  ResultTypeRefuseReasonDbValidateFailed = 6,
  ResultTypeRefuseReasonVersionTooOld = 7,
} ResultType;

BOOL ResultTypeIsValidValue(ResultType value);

typedef enum {
  KickReasonTypeKickReasonDuplicateUser = 1,
  KickReasonTypeKickReasonMobileKick = 2,
} KickReasonType;

BOOL KickReasonTypeIsValidValue(KickReasonType value);

typedef enum {
  OnlineListTypeOnlineListTypeFriendList = 1,
} OnlineListType;

BOOL OnlineListTypeIsValidValue(OnlineListType value);

typedef enum {
  UserStatTypeUserStatusOnline = 1,
  UserStatTypeUserStatusOffline = 2,
  UserStatTypeUserStatusLeave = 3,
} UserStatType;

BOOL UserStatTypeIsValidValue(UserStatType value);

typedef enum {
  SessionTypeSessionTypeSingle = 1,
  SessionTypeSessionTypeGroup = 2,
} SessionType;

BOOL SessionTypeIsValidValue(SessionType value);

typedef enum {
  MsgTypeMsgTypeSingleText = 1,
  MsgTypeMsgTypeSingleAudio = 2,
  MsgTypeMsgTypeGroupText = 17,
  MsgTypeMsgTypeGroupAudio = 18,
} MsgType;

BOOL MsgTypeIsValidValue(MsgType value);

typedef enum {
  ClientTypeClientTypeWindows = 1,
  ClientTypeClientTypeMac = 2,
  ClientTypeClientTypeIos = 17,
  ClientTypeClientTypeAndroid = 18,
} ClientType;

BOOL ClientTypeIsValidValue(ClientType value);

typedef enum {
  GroupTypeGroupTypeNormal = 1,
  GroupTypeGroupTypeTmp = 2,
} GroupType;

BOOL GroupTypeIsValidValue(GroupType value);

typedef enum {
  GroupModifyTypeGroupModifyTypeAdd = 1,
  GroupModifyTypeGroupModifyTypeDel = 2,
} GroupModifyType;

BOOL GroupModifyTypeIsValidValue(GroupModifyType value);

typedef enum {
  FileTypeFileTypeOnline = 1,
  FileTypeFileTypeOffline = 2,
} PBFileType;

BOOL FileTypeIsValidValue(PBFileType value);

typedef enum {
  ClientFileStateClientFilePeerReady = 0,
  ClientFileStateClientFileCancel = 1,
  ClientFileStateClientFileRefuse = 2,
  ClientFileStateClientFileDone = 3,
} ClientFileState;

BOOL ClientFileStateIsValidValue(ClientFileState value);

typedef enum {
  ClientFileRoleClientRealtimeSender = 1,
  ClientFileRoleClientRealtimeRecver = 2,
  ClientFileRoleClientOfflineUpload = 3,
  ClientFileRoleClientOfflineDownload = 4,
} ClientFileRole;

BOOL ClientFileRoleIsValidValue(ClientFileRole value);

typedef enum {
  FileServerErrorFileServerErrnoOk = 0,
  FileServerErrorFileServerErrnoCreateTaskIdError = 1,
  FileServerErrorFileServerErrnoCreateTaskError = 2,
  FileServerErrorFileServerErrnoLoginInvalidToken = 3,
  FileServerErrorFileServerErrnoInvalidUserForTask = 4,
  FileServerErrorFileServerErrnoPullDataWithInvalidTaskId = 5,
  FileServerErrorFileServerErrnoPullDataIllieageUser = 6,
  FileServerErrorFileServerErrnoPullDataMkdirError = 7,
  FileServerErrorFileServerErrnoPullDataOpenFileError = 8,
  FileServerErrorFileServerErrnoPullDataReadFileHeaderError = 9,
  FileServerErrorFileServerErrnoPullDataAllocMemError = 10,
  FileServerErrorFileServerErrnoPullDataSeekOffsetError = 11,
  FileServerErrorFileServerErrnoPullDataFinished = 12,
} FileServerError;

BOOL FileServerErrorIsValidValue(FileServerError value);

typedef enum {
  SessionStatusTypeSessionStatusOk = 0,
  SessionStatusTypeSessionStatusDelete = 1,
} SessionStatusType;

BOOL SessionStatusTypeIsValidValue(SessionStatusType value);

typedef enum {
  DepartmentStatusTypeDeptStatusOk = 0,
  DepartmentStatusTypeDeptStatusDelete = 1,
} DepartmentStatusType;

BOOL DepartmentStatusTypeIsValidValue(DepartmentStatusType value);


@interface ImbaseDefineRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface IpAddr : PBGeneratedMessage {
@private
  BOOL hasIp_:1;
  BOOL hasPort_:1;
  NSString* ip;
  UInt32 port;
}
- (BOOL) hasIp;
- (BOOL) hasPort;
@property (readonly, strong) NSString* ip;
@property (readonly) UInt32 port;

+ (IpAddr*) defaultInstance;
- (IpAddr*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IpAddrBuilder*) builder;
+ (IpAddrBuilder*) builder;
+ (IpAddrBuilder*) builderWithPrototype:(IpAddr*) prototype;
- (IpAddrBuilder*) toBuilder;

+ (IpAddr*) parseFromData:(NSData*) data;
+ (IpAddr*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IpAddr*) parseFromInputStream:(NSInputStream*) input;
+ (IpAddr*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IpAddr*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IpAddr*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IpAddrBuilder : PBGeneratedMessageBuilder {
@private
  IpAddr* result;
}

- (IpAddr*) defaultInstance;

- (IpAddrBuilder*) clear;
- (IpAddrBuilder*) clone;

- (IpAddr*) build;
- (IpAddr*) buildPartial;

- (IpAddrBuilder*) mergeFrom:(IpAddr*) other;
- (IpAddrBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IpAddrBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIp;
- (NSString*) ip;
- (IpAddrBuilder*) setIp:(NSString*) value;
- (IpAddrBuilder*) clearIp;

- (BOOL) hasPort;
- (UInt32) port;
- (IpAddrBuilder*) setPort:(UInt32) value;
- (IpAddrBuilder*) clearPort;
@end

@interface UserInfo : PBGeneratedMessage {
@private
  BOOL hasUserNickName_:1;
  BOOL hasAvatarUrl_:1;
  BOOL hasEmail_:1;
  BOOL hasUserRealName_:1;
  BOOL hasUserTel_:1;
  BOOL hasUserDomain_:1;
  BOOL hasUserId_:1;
  BOOL hasUserGender_:1;
  BOOL hasDepartmentId_:1;
  BOOL hasStatus_:1;
  NSString* userNickName;
  NSString* avatarUrl;
  NSString* email;
  NSString* userRealName;
  NSString* userTel;
  NSString* userDomain;
  UInt32 userId;
  UInt32 userGender;
  UInt32 departmentId;
  UInt32 status;
}
- (BOOL) hasUserId;
- (BOOL) hasUserGender;
- (BOOL) hasUserNickName;
- (BOOL) hasAvatarUrl;
- (BOOL) hasDepartmentId;
- (BOOL) hasEmail;
- (BOOL) hasUserRealName;
- (BOOL) hasUserTel;
- (BOOL) hasUserDomain;
- (BOOL) hasStatus;
@property (readonly) UInt32 userId;
@property (readonly) UInt32 userGender;
@property (readonly, strong) NSString* userNickName;
@property (readonly, strong) NSString* avatarUrl;
@property (readonly) UInt32 departmentId;
@property (readonly, strong) NSString* email;
@property (readonly, strong) NSString* userRealName;
@property (readonly, strong) NSString* userTel;
@property (readonly, strong) NSString* userDomain;
@property (readonly) UInt32 status;

+ (UserInfo*) defaultInstance;
- (UserInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserInfoBuilder*) builder;
+ (UserInfoBuilder*) builder;
+ (UserInfoBuilder*) builderWithPrototype:(UserInfo*) prototype;
- (UserInfoBuilder*) toBuilder;

+ (UserInfo*) parseFromData:(NSData*) data;
+ (UserInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserInfo*) parseFromInputStream:(NSInputStream*) input;
+ (UserInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserInfoBuilder : PBGeneratedMessageBuilder {
@private
  UserInfo* result;
}

- (UserInfo*) defaultInstance;

- (UserInfoBuilder*) clear;
- (UserInfoBuilder*) clone;

- (UserInfo*) build;
- (UserInfo*) buildPartial;

- (UserInfoBuilder*) mergeFrom:(UserInfo*) other;
- (UserInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (UserInfoBuilder*) setUserId:(UInt32) value;
- (UserInfoBuilder*) clearUserId;

- (BOOL) hasUserGender;
- (UInt32) userGender;
- (UserInfoBuilder*) setUserGender:(UInt32) value;
- (UserInfoBuilder*) clearUserGender;

- (BOOL) hasUserNickName;
- (NSString*) userNickName;
- (UserInfoBuilder*) setUserNickName:(NSString*) value;
- (UserInfoBuilder*) clearUserNickName;

- (BOOL) hasAvatarUrl;
- (NSString*) avatarUrl;
- (UserInfoBuilder*) setAvatarUrl:(NSString*) value;
- (UserInfoBuilder*) clearAvatarUrl;

- (BOOL) hasDepartmentId;
- (UInt32) departmentId;
- (UserInfoBuilder*) setDepartmentId:(UInt32) value;
- (UserInfoBuilder*) clearDepartmentId;

- (BOOL) hasEmail;
- (NSString*) email;
- (UserInfoBuilder*) setEmail:(NSString*) value;
- (UserInfoBuilder*) clearEmail;

- (BOOL) hasUserRealName;
- (NSString*) userRealName;
- (UserInfoBuilder*) setUserRealName:(NSString*) value;
- (UserInfoBuilder*) clearUserRealName;

- (BOOL) hasUserTel;
- (NSString*) userTel;
- (UserInfoBuilder*) setUserTel:(NSString*) value;
- (UserInfoBuilder*) clearUserTel;

- (BOOL) hasUserDomain;
- (NSString*) userDomain;
- (UserInfoBuilder*) setUserDomain:(NSString*) value;
- (UserInfoBuilder*) clearUserDomain;

- (BOOL) hasStatus;
- (UInt32) status;
- (UserInfoBuilder*) setStatus:(UInt32) value;
- (UserInfoBuilder*) clearStatus;
@end

@interface ContactSessionInfo : PBGeneratedMessage {
@private
  BOOL hasLatestMsgData_:1;
  BOOL hasSessionId_:1;
  BOOL hasUpdatedTime_:1;
  BOOL hasLatestMsgId_:1;
  BOOL hasLatestMsgFromUserId_:1;
  BOOL hasSessionType_:1;
  BOOL hasSessionStatus_:1;
  BOOL hasLatestMsgType_:1;
  NSData* latestMsgData;
  UInt32 sessionId;
  UInt32 updatedTime;
  UInt32 latestMsgId;
  UInt32 latestMsgFromUserId;
  SessionType sessionType;
  SessionStatusType sessionStatus;
  MsgType latestMsgType;
}
- (BOOL) hasSessionId;
- (BOOL) hasSessionType;
- (BOOL) hasSessionStatus;
- (BOOL) hasUpdatedTime;
- (BOOL) hasLatestMsgId;
- (BOOL) hasLatestMsgData;
- (BOOL) hasLatestMsgType;
- (BOOL) hasLatestMsgFromUserId;
@property (readonly) UInt32 sessionId;
@property (readonly) SessionType sessionType;
@property (readonly) SessionStatusType sessionStatus;
@property (readonly) UInt32 updatedTime;
@property (readonly) UInt32 latestMsgId;
@property (readonly, strong) NSData* latestMsgData;
@property (readonly) MsgType latestMsgType;
@property (readonly) UInt32 latestMsgFromUserId;

+ (ContactSessionInfo*) defaultInstance;
- (ContactSessionInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ContactSessionInfoBuilder*) builder;
+ (ContactSessionInfoBuilder*) builder;
+ (ContactSessionInfoBuilder*) builderWithPrototype:(ContactSessionInfo*) prototype;
- (ContactSessionInfoBuilder*) toBuilder;

+ (ContactSessionInfo*) parseFromData:(NSData*) data;
+ (ContactSessionInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ContactSessionInfo*) parseFromInputStream:(NSInputStream*) input;
+ (ContactSessionInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ContactSessionInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ContactSessionInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ContactSessionInfoBuilder : PBGeneratedMessageBuilder {
@private
  ContactSessionInfo* result;
}

- (ContactSessionInfo*) defaultInstance;

- (ContactSessionInfoBuilder*) clear;
- (ContactSessionInfoBuilder*) clone;

- (ContactSessionInfo*) build;
- (ContactSessionInfo*) buildPartial;

- (ContactSessionInfoBuilder*) mergeFrom:(ContactSessionInfo*) other;
- (ContactSessionInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ContactSessionInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSessionId;
- (UInt32) sessionId;
- (ContactSessionInfoBuilder*) setSessionId:(UInt32) value;
- (ContactSessionInfoBuilder*) clearSessionId;

- (BOOL) hasSessionType;
- (SessionType) sessionType;
- (ContactSessionInfoBuilder*) setSessionType:(SessionType) value;
- (ContactSessionInfoBuilder*) clearSessionType;

- (BOOL) hasSessionStatus;
- (SessionStatusType) sessionStatus;
- (ContactSessionInfoBuilder*) setSessionStatus:(SessionStatusType) value;
- (ContactSessionInfoBuilder*) clearSessionStatus;

- (BOOL) hasUpdatedTime;
- (UInt32) updatedTime;
- (ContactSessionInfoBuilder*) setUpdatedTime:(UInt32) value;
- (ContactSessionInfoBuilder*) clearUpdatedTime;

- (BOOL) hasLatestMsgId;
- (UInt32) latestMsgId;
- (ContactSessionInfoBuilder*) setLatestMsgId:(UInt32) value;
- (ContactSessionInfoBuilder*) clearLatestMsgId;

- (BOOL) hasLatestMsgData;
- (NSData*) latestMsgData;
- (ContactSessionInfoBuilder*) setLatestMsgData:(NSData*) value;
- (ContactSessionInfoBuilder*) clearLatestMsgData;

- (BOOL) hasLatestMsgType;
- (MsgType) latestMsgType;
- (ContactSessionInfoBuilder*) setLatestMsgType:(MsgType) value;
- (ContactSessionInfoBuilder*) clearLatestMsgType;

- (BOOL) hasLatestMsgFromUserId;
- (UInt32) latestMsgFromUserId;
- (ContactSessionInfoBuilder*) setLatestMsgFromUserId:(UInt32) value;
- (ContactSessionInfoBuilder*) clearLatestMsgFromUserId;
@end

@interface UserStat : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasStatus_:1;
  UInt32 userId;
  UserStatType status;
}
- (BOOL) hasUserId;
- (BOOL) hasStatus;
@property (readonly) UInt32 userId;
@property (readonly) UserStatType status;

+ (UserStat*) defaultInstance;
- (UserStat*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserStatBuilder*) builder;
+ (UserStatBuilder*) builder;
+ (UserStatBuilder*) builderWithPrototype:(UserStat*) prototype;
- (UserStatBuilder*) toBuilder;

+ (UserStat*) parseFromData:(NSData*) data;
+ (UserStat*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserStat*) parseFromInputStream:(NSInputStream*) input;
+ (UserStat*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserStat*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserStat*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserStatBuilder : PBGeneratedMessageBuilder {
@private
  UserStat* result;
}

- (UserStat*) defaultInstance;

- (UserStatBuilder*) clear;
- (UserStatBuilder*) clone;

- (UserStat*) build;
- (UserStat*) buildPartial;

- (UserStatBuilder*) mergeFrom:(UserStat*) other;
- (UserStatBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserStatBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (UserStatBuilder*) setUserId:(UInt32) value;
- (UserStatBuilder*) clearUserId;

- (BOOL) hasStatus;
- (UserStatType) status;
- (UserStatBuilder*) setStatus:(UserStatType) value;
- (UserStatBuilder*) clearStatus;
@end

@interface ServerUserStat : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasStatus_:1;
  BOOL hasClientType_:1;
  UInt32 userId;
  UserStatType status;
  ClientType clientType;
}
- (BOOL) hasUserId;
- (BOOL) hasStatus;
- (BOOL) hasClientType;
@property (readonly) UInt32 userId;
@property (readonly) UserStatType status;
@property (readonly) ClientType clientType;

+ (ServerUserStat*) defaultInstance;
- (ServerUserStat*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ServerUserStatBuilder*) builder;
+ (ServerUserStatBuilder*) builder;
+ (ServerUserStatBuilder*) builderWithPrototype:(ServerUserStat*) prototype;
- (ServerUserStatBuilder*) toBuilder;

+ (ServerUserStat*) parseFromData:(NSData*) data;
+ (ServerUserStat*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServerUserStat*) parseFromInputStream:(NSInputStream*) input;
+ (ServerUserStat*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServerUserStat*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ServerUserStat*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ServerUserStatBuilder : PBGeneratedMessageBuilder {
@private
  ServerUserStat* result;
}

- (ServerUserStat*) defaultInstance;

- (ServerUserStatBuilder*) clear;
- (ServerUserStatBuilder*) clone;

- (ServerUserStat*) build;
- (ServerUserStat*) buildPartial;

- (ServerUserStatBuilder*) mergeFrom:(ServerUserStat*) other;
- (ServerUserStatBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ServerUserStatBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (ServerUserStatBuilder*) setUserId:(UInt32) value;
- (ServerUserStatBuilder*) clearUserId;

- (BOOL) hasStatus;
- (UserStatType) status;
- (ServerUserStatBuilder*) setStatus:(UserStatType) value;
- (ServerUserStatBuilder*) clearStatus;

- (BOOL) hasClientType;
- (ClientType) clientType;
- (ServerUserStatBuilder*) setClientType:(ClientType) value;
- (ServerUserStatBuilder*) clearClientType;
@end

@interface UnreadInfo : PBGeneratedMessage {
@private
  BOOL hasLatestMsgData_:1;
  BOOL hasSessionId_:1;
  BOOL hasUnreadCnt_:1;
  BOOL hasLatestMsgId_:1;
  BOOL hasLatestMsgFromUserId_:1;
  BOOL hasSessionType_:1;
  BOOL hasLatestMsgType_:1;
  NSData* latestMsgData;
  UInt32 sessionId;
  UInt32 unreadCnt;
  UInt32 latestMsgId;
  UInt32 latestMsgFromUserId;
  SessionType sessionType;
  MsgType latestMsgType;
}
- (BOOL) hasSessionId;
- (BOOL) hasSessionType;
- (BOOL) hasUnreadCnt;
- (BOOL) hasLatestMsgId;
- (BOOL) hasLatestMsgData;
- (BOOL) hasLatestMsgType;
- (BOOL) hasLatestMsgFromUserId;
@property (readonly) UInt32 sessionId;
@property (readonly) SessionType sessionType;
@property (readonly) UInt32 unreadCnt;
@property (readonly) UInt32 latestMsgId;
@property (readonly, strong) NSData* latestMsgData;
@property (readonly) MsgType latestMsgType;
@property (readonly) UInt32 latestMsgFromUserId;

+ (UnreadInfo*) defaultInstance;
- (UnreadInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UnreadInfoBuilder*) builder;
+ (UnreadInfoBuilder*) builder;
+ (UnreadInfoBuilder*) builderWithPrototype:(UnreadInfo*) prototype;
- (UnreadInfoBuilder*) toBuilder;

+ (UnreadInfo*) parseFromData:(NSData*) data;
+ (UnreadInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UnreadInfo*) parseFromInputStream:(NSInputStream*) input;
+ (UnreadInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UnreadInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UnreadInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UnreadInfoBuilder : PBGeneratedMessageBuilder {
@private
  UnreadInfo* result;
}

- (UnreadInfo*) defaultInstance;

- (UnreadInfoBuilder*) clear;
- (UnreadInfoBuilder*) clone;

- (UnreadInfo*) build;
- (UnreadInfo*) buildPartial;

- (UnreadInfoBuilder*) mergeFrom:(UnreadInfo*) other;
- (UnreadInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UnreadInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSessionId;
- (UInt32) sessionId;
- (UnreadInfoBuilder*) setSessionId:(UInt32) value;
- (UnreadInfoBuilder*) clearSessionId;

- (BOOL) hasSessionType;
- (SessionType) sessionType;
- (UnreadInfoBuilder*) setSessionType:(SessionType) value;
- (UnreadInfoBuilder*) clearSessionType;

- (BOOL) hasUnreadCnt;
- (UInt32) unreadCnt;
- (UnreadInfoBuilder*) setUnreadCnt:(UInt32) value;
- (UnreadInfoBuilder*) clearUnreadCnt;

- (BOOL) hasLatestMsgId;
- (UInt32) latestMsgId;
- (UnreadInfoBuilder*) setLatestMsgId:(UInt32) value;
- (UnreadInfoBuilder*) clearLatestMsgId;

- (BOOL) hasLatestMsgData;
- (NSData*) latestMsgData;
- (UnreadInfoBuilder*) setLatestMsgData:(NSData*) value;
- (UnreadInfoBuilder*) clearLatestMsgData;

- (BOOL) hasLatestMsgType;
- (MsgType) latestMsgType;
- (UnreadInfoBuilder*) setLatestMsgType:(MsgType) value;
- (UnreadInfoBuilder*) clearLatestMsgType;

- (BOOL) hasLatestMsgFromUserId;
- (UInt32) latestMsgFromUserId;
- (UnreadInfoBuilder*) setLatestMsgFromUserId:(UInt32) value;
- (UnreadInfoBuilder*) clearLatestMsgFromUserId;
@end

@interface MsgInfo : PBGeneratedMessage {
@private
  BOOL hasMsgData_:1;
  BOOL hasMsgId_:1;
  BOOL hasFromSessionId_:1;
  BOOL hasCreateTime_:1;
  BOOL hasMsgType_:1;
  NSData* msgData;
  UInt32 msgId;
  UInt32 fromSessionId;
  UInt32 createTime;
  MsgType msgType;
}
- (BOOL) hasMsgId;
- (BOOL) hasFromSessionId;
- (BOOL) hasCreateTime;
- (BOOL) hasMsgType;
- (BOOL) hasMsgData;
@property (readonly) UInt32 msgId;
@property (readonly) UInt32 fromSessionId;
@property (readonly) UInt32 createTime;
@property (readonly) MsgType msgType;
@property (readonly, strong) NSData* msgData;

+ (MsgInfo*) defaultInstance;
- (MsgInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgInfoBuilder*) builder;
+ (MsgInfoBuilder*) builder;
+ (MsgInfoBuilder*) builderWithPrototype:(MsgInfo*) prototype;
- (MsgInfoBuilder*) toBuilder;

+ (MsgInfo*) parseFromData:(NSData*) data;
+ (MsgInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgInfo*) parseFromInputStream:(NSInputStream*) input;
+ (MsgInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgInfoBuilder : PBGeneratedMessageBuilder {
@private
  MsgInfo* result;
}

- (MsgInfo*) defaultInstance;

- (MsgInfoBuilder*) clear;
- (MsgInfoBuilder*) clone;

- (MsgInfo*) build;
- (MsgInfo*) buildPartial;

- (MsgInfoBuilder*) mergeFrom:(MsgInfo*) other;
- (MsgInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMsgId;
- (UInt32) msgId;
- (MsgInfoBuilder*) setMsgId:(UInt32) value;
- (MsgInfoBuilder*) clearMsgId;

- (BOOL) hasFromSessionId;
- (UInt32) fromSessionId;
- (MsgInfoBuilder*) setFromSessionId:(UInt32) value;
- (MsgInfoBuilder*) clearFromSessionId;

- (BOOL) hasCreateTime;
- (UInt32) createTime;
- (MsgInfoBuilder*) setCreateTime:(UInt32) value;
- (MsgInfoBuilder*) clearCreateTime;

- (BOOL) hasMsgType;
- (MsgType) msgType;
- (MsgInfoBuilder*) setMsgType:(MsgType) value;
- (MsgInfoBuilder*) clearMsgType;

- (BOOL) hasMsgData;
- (NSData*) msgData;
- (MsgInfoBuilder*) setMsgData:(NSData*) value;
- (MsgInfoBuilder*) clearMsgData;
@end

@interface GroupVersionInfo : PBGeneratedMessage {
@private
  BOOL hasGroupId_:1;
  BOOL hasVersion_:1;
  UInt32 groupId;
  UInt32 version;
}
- (BOOL) hasGroupId;
- (BOOL) hasVersion;
@property (readonly) UInt32 groupId;
@property (readonly) UInt32 version;

+ (GroupVersionInfo*) defaultInstance;
- (GroupVersionInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GroupVersionInfoBuilder*) builder;
+ (GroupVersionInfoBuilder*) builder;
+ (GroupVersionInfoBuilder*) builderWithPrototype:(GroupVersionInfo*) prototype;
- (GroupVersionInfoBuilder*) toBuilder;

+ (GroupVersionInfo*) parseFromData:(NSData*) data;
+ (GroupVersionInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GroupVersionInfo*) parseFromInputStream:(NSInputStream*) input;
+ (GroupVersionInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GroupVersionInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GroupVersionInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GroupVersionInfoBuilder : PBGeneratedMessageBuilder {
@private
  GroupVersionInfo* result;
}

- (GroupVersionInfo*) defaultInstance;

- (GroupVersionInfoBuilder*) clear;
- (GroupVersionInfoBuilder*) clone;

- (GroupVersionInfo*) build;
- (GroupVersionInfo*) buildPartial;

- (GroupVersionInfoBuilder*) mergeFrom:(GroupVersionInfo*) other;
- (GroupVersionInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GroupVersionInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (UInt32) groupId;
- (GroupVersionInfoBuilder*) setGroupId:(UInt32) value;
- (GroupVersionInfoBuilder*) clearGroupId;

- (BOOL) hasVersion;
- (UInt32) version;
- (GroupVersionInfoBuilder*) setVersion:(UInt32) value;
- (GroupVersionInfoBuilder*) clearVersion;
@end

@interface GroupInfo : PBGeneratedMessage {
@private
  BOOL hasGroupName_:1;
  BOOL hasGroupAvatar_:1;
  BOOL hasGroupId_:1;
  BOOL hasVersion_:1;
  BOOL hasGroupCreatorId_:1;
  BOOL hasShieldStatus_:1;
  BOOL hasGroupType_:1;
  NSString* groupName;
  NSString* groupAvatar;
  UInt32 groupId;
  UInt32 version;
  UInt32 groupCreatorId;
  UInt32 shieldStatus;
  GroupType groupType;
  PBAppendableArray * groupMemberListArray;
}
- (BOOL) hasGroupId;
- (BOOL) hasVersion;
- (BOOL) hasGroupName;
- (BOOL) hasGroupAvatar;
- (BOOL) hasGroupCreatorId;
- (BOOL) hasGroupType;
- (BOOL) hasShieldStatus;
@property (readonly) UInt32 groupId;
@property (readonly) UInt32 version;
@property (readonly, strong) NSString* groupName;
@property (readonly, strong) NSString* groupAvatar;
@property (readonly) UInt32 groupCreatorId;
@property (readonly) GroupType groupType;
@property (readonly) UInt32 shieldStatus;
@property (readonly, strong) PBArray * groupMemberList;
- (UInt32)groupMemberListAtIndex:(NSUInteger)index;

+ (GroupInfo*) defaultInstance;
- (GroupInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GroupInfoBuilder*) builder;
+ (GroupInfoBuilder*) builder;
+ (GroupInfoBuilder*) builderWithPrototype:(GroupInfo*) prototype;
- (GroupInfoBuilder*) toBuilder;

+ (GroupInfo*) parseFromData:(NSData*) data;
+ (GroupInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GroupInfo*) parseFromInputStream:(NSInputStream*) input;
+ (GroupInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GroupInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GroupInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GroupInfoBuilder : PBGeneratedMessageBuilder {
@private
  GroupInfo* result;
}

- (GroupInfo*) defaultInstance;

- (GroupInfoBuilder*) clear;
- (GroupInfoBuilder*) clone;

- (GroupInfo*) build;
- (GroupInfo*) buildPartial;

- (GroupInfoBuilder*) mergeFrom:(GroupInfo*) other;
- (GroupInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GroupInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (UInt32) groupId;
- (GroupInfoBuilder*) setGroupId:(UInt32) value;
- (GroupInfoBuilder*) clearGroupId;

- (BOOL) hasVersion;
- (UInt32) version;
- (GroupInfoBuilder*) setVersion:(UInt32) value;
- (GroupInfoBuilder*) clearVersion;

- (BOOL) hasGroupName;
- (NSString*) groupName;
- (GroupInfoBuilder*) setGroupName:(NSString*) value;
- (GroupInfoBuilder*) clearGroupName;

- (BOOL) hasGroupAvatar;
- (NSString*) groupAvatar;
- (GroupInfoBuilder*) setGroupAvatar:(NSString*) value;
- (GroupInfoBuilder*) clearGroupAvatar;

- (BOOL) hasGroupCreatorId;
- (UInt32) groupCreatorId;
- (GroupInfoBuilder*) setGroupCreatorId:(UInt32) value;
- (GroupInfoBuilder*) clearGroupCreatorId;

- (BOOL) hasGroupType;
- (GroupType) groupType;
- (GroupInfoBuilder*) setGroupType:(GroupType) value;
- (GroupInfoBuilder*) clearGroupType;

- (BOOL) hasShieldStatus;
- (UInt32) shieldStatus;
- (GroupInfoBuilder*) setShieldStatus:(UInt32) value;
- (GroupInfoBuilder*) clearShieldStatus;

- (PBAppendableArray *)groupMemberList;
- (UInt32)groupMemberListAtIndex:(NSUInteger)index;
- (GroupInfoBuilder *)addGroupMemberList:(UInt32)value;
- (GroupInfoBuilder *)setGroupMemberListArray:(NSArray *)array;
- (GroupInfoBuilder *)setGroupMemberListValues:(const UInt32 *)values count:(NSUInteger)count;
- (GroupInfoBuilder *)clearGroupMemberList;
@end

@interface UserTokenInfo : PBGeneratedMessage {
@private
  BOOL hasToken_:1;
  BOOL hasUserId_:1;
  BOOL hasPushCount_:1;
  BOOL hasPushType_:1;
  BOOL hasUserType_:1;
  NSString* token;
  UInt32 userId;
  UInt32 pushCount;
  UInt32 pushType;
  ClientType userType;
}
- (BOOL) hasUserId;
- (BOOL) hasUserType;
- (BOOL) hasToken;
- (BOOL) hasPushCount;
- (BOOL) hasPushType;
@property (readonly) UInt32 userId;
@property (readonly) ClientType userType;
@property (readonly, strong) NSString* token;
@property (readonly) UInt32 pushCount;
@property (readonly) UInt32 pushType;

+ (UserTokenInfo*) defaultInstance;
- (UserTokenInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserTokenInfoBuilder*) builder;
+ (UserTokenInfoBuilder*) builder;
+ (UserTokenInfoBuilder*) builderWithPrototype:(UserTokenInfo*) prototype;
- (UserTokenInfoBuilder*) toBuilder;

+ (UserTokenInfo*) parseFromData:(NSData*) data;
+ (UserTokenInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserTokenInfo*) parseFromInputStream:(NSInputStream*) input;
+ (UserTokenInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserTokenInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserTokenInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserTokenInfoBuilder : PBGeneratedMessageBuilder {
@private
  UserTokenInfo* result;
}

- (UserTokenInfo*) defaultInstance;

- (UserTokenInfoBuilder*) clear;
- (UserTokenInfoBuilder*) clone;

- (UserTokenInfo*) build;
- (UserTokenInfo*) buildPartial;

- (UserTokenInfoBuilder*) mergeFrom:(UserTokenInfo*) other;
- (UserTokenInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserTokenInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (UserTokenInfoBuilder*) setUserId:(UInt32) value;
- (UserTokenInfoBuilder*) clearUserId;

- (BOOL) hasUserType;
- (ClientType) userType;
- (UserTokenInfoBuilder*) setUserType:(ClientType) value;
- (UserTokenInfoBuilder*) clearUserType;

- (BOOL) hasToken;
- (NSString*) token;
- (UserTokenInfoBuilder*) setToken:(NSString*) value;
- (UserTokenInfoBuilder*) clearToken;

- (BOOL) hasPushCount;
- (UInt32) pushCount;
- (UserTokenInfoBuilder*) setPushCount:(UInt32) value;
- (UserTokenInfoBuilder*) clearPushCount;

- (BOOL) hasPushType;
- (UInt32) pushType;
- (UserTokenInfoBuilder*) setPushType:(UInt32) value;
- (UserTokenInfoBuilder*) clearPushType;
@end

@interface PushResult : PBGeneratedMessage {
@private
  BOOL hasUserToken_:1;
  BOOL hasResultCode_:1;
  NSString* userToken;
  UInt32 resultCode;
}
- (BOOL) hasUserToken;
- (BOOL) hasResultCode;
@property (readonly, strong) NSString* userToken;
@property (readonly) UInt32 resultCode;

+ (PushResult*) defaultInstance;
- (PushResult*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PushResultBuilder*) builder;
+ (PushResultBuilder*) builder;
+ (PushResultBuilder*) builderWithPrototype:(PushResult*) prototype;
- (PushResultBuilder*) toBuilder;

+ (PushResult*) parseFromData:(NSData*) data;
+ (PushResult*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PushResult*) parseFromInputStream:(NSInputStream*) input;
+ (PushResult*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PushResult*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PushResult*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PushResultBuilder : PBGeneratedMessageBuilder {
@private
  PushResult* result;
}

- (PushResult*) defaultInstance;

- (PushResultBuilder*) clear;
- (PushResultBuilder*) clone;

- (PushResult*) build;
- (PushResult*) buildPartial;

- (PushResultBuilder*) mergeFrom:(PushResult*) other;
- (PushResultBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PushResultBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserToken;
- (NSString*) userToken;
- (PushResultBuilder*) setUserToken:(NSString*) value;
- (PushResultBuilder*) clearUserToken;

- (BOOL) hasResultCode;
- (UInt32) resultCode;
- (PushResultBuilder*) setResultCode:(UInt32) value;
- (PushResultBuilder*) clearResultCode;
@end

@interface ShieldStatus : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasGroupId_:1;
  BOOL hasShieldStatus_:1;
  UInt32 userId;
  UInt32 groupId;
  UInt32 shieldStatus;
}
- (BOOL) hasUserId;
- (BOOL) hasGroupId;
- (BOOL) hasShieldStatus;
@property (readonly) UInt32 userId;
@property (readonly) UInt32 groupId;
@property (readonly) UInt32 shieldStatus;

+ (ShieldStatus*) defaultInstance;
- (ShieldStatus*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ShieldStatusBuilder*) builder;
+ (ShieldStatusBuilder*) builder;
+ (ShieldStatusBuilder*) builderWithPrototype:(ShieldStatus*) prototype;
- (ShieldStatusBuilder*) toBuilder;

+ (ShieldStatus*) parseFromData:(NSData*) data;
+ (ShieldStatus*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ShieldStatus*) parseFromInputStream:(NSInputStream*) input;
+ (ShieldStatus*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ShieldStatus*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ShieldStatus*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ShieldStatusBuilder : PBGeneratedMessageBuilder {
@private
  ShieldStatus* result;
}

- (ShieldStatus*) defaultInstance;

- (ShieldStatusBuilder*) clear;
- (ShieldStatusBuilder*) clone;

- (ShieldStatus*) build;
- (ShieldStatus*) buildPartial;

- (ShieldStatusBuilder*) mergeFrom:(ShieldStatus*) other;
- (ShieldStatusBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ShieldStatusBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (ShieldStatusBuilder*) setUserId:(UInt32) value;
- (ShieldStatusBuilder*) clearUserId;

- (BOOL) hasGroupId;
- (UInt32) groupId;
- (ShieldStatusBuilder*) setGroupId:(UInt32) value;
- (ShieldStatusBuilder*) clearGroupId;

- (BOOL) hasShieldStatus;
- (UInt32) shieldStatus;
- (ShieldStatusBuilder*) setShieldStatus:(UInt32) value;
- (ShieldStatusBuilder*) clearShieldStatus;
@end

@interface OfflineFileInfo : PBGeneratedMessage {
@private
  BOOL hasTaskId_:1;
  BOOL hasFileName_:1;
  BOOL hasFromUserId_:1;
  BOOL hasFileSize_:1;
  NSString* taskId;
  NSString* fileName;
  UInt32 fromUserId;
  UInt32 fileSize;
}
- (BOOL) hasFromUserId;
- (BOOL) hasTaskId;
- (BOOL) hasFileName;
- (BOOL) hasFileSize;
@property (readonly) UInt32 fromUserId;
@property (readonly, strong) NSString* taskId;
@property (readonly, strong) NSString* fileName;
@property (readonly) UInt32 fileSize;

+ (OfflineFileInfo*) defaultInstance;
- (OfflineFileInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (OfflineFileInfoBuilder*) builder;
+ (OfflineFileInfoBuilder*) builder;
+ (OfflineFileInfoBuilder*) builderWithPrototype:(OfflineFileInfo*) prototype;
- (OfflineFileInfoBuilder*) toBuilder;

+ (OfflineFileInfo*) parseFromData:(NSData*) data;
+ (OfflineFileInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OfflineFileInfo*) parseFromInputStream:(NSInputStream*) input;
+ (OfflineFileInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OfflineFileInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (OfflineFileInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface OfflineFileInfoBuilder : PBGeneratedMessageBuilder {
@private
  OfflineFileInfo* result;
}

- (OfflineFileInfo*) defaultInstance;

- (OfflineFileInfoBuilder*) clear;
- (OfflineFileInfoBuilder*) clone;

- (OfflineFileInfo*) build;
- (OfflineFileInfo*) buildPartial;

- (OfflineFileInfoBuilder*) mergeFrom:(OfflineFileInfo*) other;
- (OfflineFileInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (OfflineFileInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromUserId;
- (UInt32) fromUserId;
- (OfflineFileInfoBuilder*) setFromUserId:(UInt32) value;
- (OfflineFileInfoBuilder*) clearFromUserId;

- (BOOL) hasTaskId;
- (NSString*) taskId;
- (OfflineFileInfoBuilder*) setTaskId:(NSString*) value;
- (OfflineFileInfoBuilder*) clearTaskId;

- (BOOL) hasFileName;
- (NSString*) fileName;
- (OfflineFileInfoBuilder*) setFileName:(NSString*) value;
- (OfflineFileInfoBuilder*) clearFileName;

- (BOOL) hasFileSize;
- (UInt32) fileSize;
- (OfflineFileInfoBuilder*) setFileSize:(UInt32) value;
- (OfflineFileInfoBuilder*) clearFileSize;
@end

@interface AuthInfo : PBGeneratedMessage {
@private
  BOOL hasAppKey_:1;
  BOOL hasAllowdUserIds_:1;
  BOOL hasAllowdGroupIds_:1;
  BOOL hasAuthInterfaces_:1;
  BOOL hasAuthIps_:1;
  BOOL hasUserId_:1;
  NSString* appKey;
  NSString* allowdUserIds;
  NSString* allowdGroupIds;
  NSString* authInterfaces;
  NSString* authIps;
  UInt32 userId;
}
- (BOOL) hasAppKey;
- (BOOL) hasUserId;
- (BOOL) hasAllowdUserIds;
- (BOOL) hasAllowdGroupIds;
- (BOOL) hasAuthInterfaces;
- (BOOL) hasAuthIps;
@property (readonly, strong) NSString* appKey;
@property (readonly) UInt32 userId;
@property (readonly, strong) NSString* allowdUserIds;
@property (readonly, strong) NSString* allowdGroupIds;
@property (readonly, strong) NSString* authInterfaces;
@property (readonly, strong) NSString* authIps;

+ (AuthInfo*) defaultInstance;
- (AuthInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AuthInfoBuilder*) builder;
+ (AuthInfoBuilder*) builder;
+ (AuthInfoBuilder*) builderWithPrototype:(AuthInfo*) prototype;
- (AuthInfoBuilder*) toBuilder;

+ (AuthInfo*) parseFromData:(NSData*) data;
+ (AuthInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AuthInfo*) parseFromInputStream:(NSInputStream*) input;
+ (AuthInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AuthInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AuthInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AuthInfoBuilder : PBGeneratedMessageBuilder {
@private
  AuthInfo* result;
}

- (AuthInfo*) defaultInstance;

- (AuthInfoBuilder*) clear;
- (AuthInfoBuilder*) clone;

- (AuthInfo*) build;
- (AuthInfo*) buildPartial;

- (AuthInfoBuilder*) mergeFrom:(AuthInfo*) other;
- (AuthInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AuthInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAppKey;
- (NSString*) appKey;
- (AuthInfoBuilder*) setAppKey:(NSString*) value;
- (AuthInfoBuilder*) clearAppKey;

- (BOOL) hasUserId;
- (UInt32) userId;
- (AuthInfoBuilder*) setUserId:(UInt32) value;
- (AuthInfoBuilder*) clearUserId;

- (BOOL) hasAllowdUserIds;
- (NSString*) allowdUserIds;
- (AuthInfoBuilder*) setAllowdUserIds:(NSString*) value;
- (AuthInfoBuilder*) clearAllowdUserIds;

- (BOOL) hasAllowdGroupIds;
- (NSString*) allowdGroupIds;
- (AuthInfoBuilder*) setAllowdGroupIds:(NSString*) value;
- (AuthInfoBuilder*) clearAllowdGroupIds;

- (BOOL) hasAuthInterfaces;
- (NSString*) authInterfaces;
- (AuthInfoBuilder*) setAuthInterfaces:(NSString*) value;
- (AuthInfoBuilder*) clearAuthInterfaces;

- (BOOL) hasAuthIps;
- (NSString*) authIps;
- (AuthInfoBuilder*) setAuthIps:(NSString*) value;
- (AuthInfoBuilder*) clearAuthIps;
@end

@interface DepartInfo : PBGeneratedMessage {
@private
  BOOL hasDeptName_:1;
  BOOL hasDeptId_:1;
  BOOL hasPriority_:1;
  BOOL hasParentDeptId_:1;
  BOOL hasDeptStatus_:1;
  NSString* deptName;
  UInt32 deptId;
  UInt32 priority;
  UInt32 parentDeptId;
  DepartmentStatusType deptStatus;
}
- (BOOL) hasDeptId;
- (BOOL) hasPriority;
- (BOOL) hasDeptName;
- (BOOL) hasParentDeptId;
- (BOOL) hasDeptStatus;
@property (readonly) UInt32 deptId;
@property (readonly) UInt32 priority;
@property (readonly, strong) NSString* deptName;
@property (readonly) UInt32 parentDeptId;
@property (readonly) DepartmentStatusType deptStatus;

+ (DepartInfo*) defaultInstance;
- (DepartInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DepartInfoBuilder*) builder;
+ (DepartInfoBuilder*) builder;
+ (DepartInfoBuilder*) builderWithPrototype:(DepartInfo*) prototype;
- (DepartInfoBuilder*) toBuilder;

+ (DepartInfo*) parseFromData:(NSData*) data;
+ (DepartInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DepartInfo*) parseFromInputStream:(NSInputStream*) input;
+ (DepartInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DepartInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DepartInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DepartInfoBuilder : PBGeneratedMessageBuilder {
@private
  DepartInfo* result;
}

- (DepartInfo*) defaultInstance;

- (DepartInfoBuilder*) clear;
- (DepartInfoBuilder*) clone;

- (DepartInfo*) build;
- (DepartInfo*) buildPartial;

- (DepartInfoBuilder*) mergeFrom:(DepartInfo*) other;
- (DepartInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DepartInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDeptId;
- (UInt32) deptId;
- (DepartInfoBuilder*) setDeptId:(UInt32) value;
- (DepartInfoBuilder*) clearDeptId;

- (BOOL) hasPriority;
- (UInt32) priority;
- (DepartInfoBuilder*) setPriority:(UInt32) value;
- (DepartInfoBuilder*) clearPriority;

- (BOOL) hasDeptName;
- (NSString*) deptName;
- (DepartInfoBuilder*) setDeptName:(NSString*) value;
- (DepartInfoBuilder*) clearDeptName;

- (BOOL) hasParentDeptId;
- (UInt32) parentDeptId;
- (DepartInfoBuilder*) setParentDeptId:(UInt32) value;
- (DepartInfoBuilder*) clearParentDeptId;

- (BOOL) hasDeptStatus;
- (DepartmentStatusType) deptStatus;
- (DepartInfoBuilder*) setDeptStatus:(DepartmentStatusType) value;
- (DepartInfoBuilder*) clearDeptStatus;
@end


// @@protoc_insertion_point(global_scope)
