// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class IMHeartBeat;
@class IMHeartBeatBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface ImotherRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface IMHeartBeat : PBGeneratedMessage {
@private
}

+ (IMHeartBeat*) defaultInstance;
- (IMHeartBeat*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMHeartBeatBuilder*) builder;
+ (IMHeartBeatBuilder*) builder;
+ (IMHeartBeatBuilder*) builderWithPrototype:(IMHeartBeat*) prototype;
- (IMHeartBeatBuilder*) toBuilder;

+ (IMHeartBeat*) parseFromData:(NSData*) data;
+ (IMHeartBeat*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMHeartBeat*) parseFromInputStream:(NSInputStream*) input;
+ (IMHeartBeat*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMHeartBeat*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMHeartBeat*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMHeartBeatBuilder : PBGeneratedMessageBuilder {
@private
  IMHeartBeat* result;
}

- (IMHeartBeat*) defaultInstance;

- (IMHeartBeatBuilder*) clear;
- (IMHeartBeatBuilder*) clone;

- (IMHeartBeat*) build;
- (IMHeartBeat*) buildPartial;

- (IMHeartBeatBuilder*) mergeFrom:(IMHeartBeat*) other;
- (IMHeartBeatBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMHeartBeatBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end


// @@protoc_insertion_point(global_scope)
