// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class IMP2PCmdMsg;
@class IMP2PCmdMsgBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface ImswitchServiceRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface IMP2PCmdMsg : PBGeneratedMessage {
@private
  BOOL hasCmdMsgData_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  NSString* cmdMsgData;
  UInt32 fromUserId;
  UInt32 toUserId;
}
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasCmdMsgData;
@property (readonly) UInt32 fromUserId;
@property (readonly) UInt32 toUserId;
@property (readonly, strong) NSString* cmdMsgData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMP2PCmdMsgBuilder*) builder;
+ (IMP2PCmdMsgBuilder*) builder;
+ (IMP2PCmdMsgBuilder*) builderWithPrototype:(IMP2PCmdMsg*) prototype;
- (IMP2PCmdMsgBuilder*) toBuilder;

+ (IMP2PCmdMsg*) parseFromData:(NSData*) data;
+ (IMP2PCmdMsg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMP2PCmdMsg*) parseFromInputStream:(NSInputStream*) input;
+ (IMP2PCmdMsg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMP2PCmdMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMP2PCmdMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMP2PCmdMsgBuilder : PBGeneratedMessageBuilder {
@private
  IMP2PCmdMsg* resultImp2PcmdMsg;
}

- (IMP2PCmdMsg*) defaultInstance;

- (IMP2PCmdMsgBuilder*) clear;
- (IMP2PCmdMsgBuilder*) clone;

- (IMP2PCmdMsg*) build;
- (IMP2PCmdMsg*) buildPartial;

- (IMP2PCmdMsgBuilder*) mergeFrom:(IMP2PCmdMsg*) other;
- (IMP2PCmdMsgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMP2PCmdMsgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromUserId;
- (UInt32) fromUserId;
- (IMP2PCmdMsgBuilder*) setFromUserId:(UInt32) value;
- (IMP2PCmdMsgBuilder*) clearFromUserId;

- (BOOL) hasToUserId;
- (UInt32) toUserId;
- (IMP2PCmdMsgBuilder*) setToUserId:(UInt32) value;
- (IMP2PCmdMsgBuilder*) clearToUserId;

- (BOOL) hasCmdMsgData;
- (NSString*) cmdMsgData;
- (IMP2PCmdMsgBuilder*) setCmdMsgData:(NSString*) value;
- (IMP2PCmdMsgBuilder*) clearCmdMsgData;
@end


// @@protoc_insertion_point(global_scope)
