// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "IMBaseDefine.pb.h"
// @@protoc_insertion_point(imports)

@class ContactSessionInfo;
@class ContactSessionInfoBuilder;
@class DepartInfo;
@class DepartInfoBuilder;
@class GroupInfo;
@class GroupInfoBuilder;
@class GroupVersionInfo;
@class GroupVersionInfoBuilder;
@class IMAllUserReq;
@class IMAllUserReqBuilder;
@class IMAllUserRsp;
@class IMAllUserRspBuilder;
@class IMAvatarChangedNotify;
@class IMAvatarChangedNotifyBuilder;
@class IMChangeAvatarReq;
@class IMChangeAvatarReqBuilder;
@class IMChangeAvatarRsp;
@class IMChangeAvatarRspBuilder;
@class IMChangeSignInfoReq;
@class IMChangeSignInfoReqBuilder;
@class IMChangeSignInfoRsp;
@class IMChangeSignInfoRspBuilder;
@class IMDepartmentReq;
@class IMDepartmentReqBuilder;
@class IMDepartmentRsp;
@class IMDepartmentRspBuilder;
@class IMPCLoginStatusNotify;
@class IMPCLoginStatusNotifyBuilder;
@class IMRecentContactSessionReq;
@class IMRecentContactSessionReqBuilder;
@class IMRecentContactSessionRsp;
@class IMRecentContactSessionRspBuilder;
@class IMRemoveSessionNotify;
@class IMRemoveSessionNotifyBuilder;
@class IMRemoveSessionReq;
@class IMRemoveSessionReqBuilder;
@class IMRemoveSessionRsp;
@class IMRemoveSessionRspBuilder;
@class IMSignInfoChangedNotify;
@class IMSignInfoChangedNotifyBuilder;
@class IMUserStatNotify;
@class IMUserStatNotifyBuilder;
@class IMUsersInfoReq;
@class IMUsersInfoReqBuilder;
@class IMUsersInfoRsp;
@class IMUsersInfoRspBuilder;
@class IMUsersStatReq;
@class IMUsersStatReqBuilder;
@class IMUsersStatRsp;
@class IMUsersStatRspBuilder;
@class IpAddr;
@class IpAddrBuilder;
@class MsgInfo;
@class MsgInfoBuilder;
@class OfflineFileInfo;
@class OfflineFileInfoBuilder;
@class PushResult;
@class PushResultBuilder;
@class PushShieldStatus;
@class PushShieldStatusBuilder;
@class ServerUserStat;
@class ServerUserStatBuilder;
@class ShieldStatus;
@class ShieldStatusBuilder;
@class UnreadInfo;
@class UnreadInfoBuilder;
@class UserInfo;
@class UserInfoBuilder;
@class UserStat;
@class UserStatBuilder;
@class UserTokenInfo;
@class UserTokenInfoBuilder;



@interface ImbuddyRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define IMRecentContactSessionReq_user_id @"userId"
#define IMRecentContactSessionReq_latest_update_time @"latestUpdateTime"
#define IMRecentContactSessionReq_attach_data @"attachData"
@interface IMRecentContactSessionReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAttachData_:1;
  BOOL hasUserId_:1;
  BOOL hasLatestUpdateTime_:1;
  NSData* attachData;
  UInt32 userId;
  UInt32 latestUpdateTime;
}
- (BOOL) hasUserId;
- (BOOL) hasLatestUpdateTime;
- (BOOL) hasAttachData;
@property (readonly) UInt32 userId;
@property (readonly) UInt32 latestUpdateTime;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMRecentContactSessionReqBuilder*) builder;
+ (IMRecentContactSessionReqBuilder*) builder;
+ (IMRecentContactSessionReqBuilder*) builderWithPrototype:(IMRecentContactSessionReq*) prototype;
- (IMRecentContactSessionReqBuilder*) toBuilder;

+ (IMRecentContactSessionReq*) parseFromData:(NSData*) data;
+ (IMRecentContactSessionReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMRecentContactSessionReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMRecentContactSessionReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMRecentContactSessionReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMRecentContactSessionReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMRecentContactSessionReqBuilder : PBGeneratedMessageBuilder {
@private
  IMRecentContactSessionReq* resultImrecentContactSessionReq;
}

- (IMRecentContactSessionReq*) defaultInstance;

- (IMRecentContactSessionReqBuilder*) clear;
- (IMRecentContactSessionReqBuilder*) clone;

- (IMRecentContactSessionReq*) build;
- (IMRecentContactSessionReq*) buildPartial;

- (IMRecentContactSessionReqBuilder*) mergeFrom:(IMRecentContactSessionReq*) other;
- (IMRecentContactSessionReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMRecentContactSessionReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (IMRecentContactSessionReqBuilder*) setUserId:(UInt32) value;
- (IMRecentContactSessionReqBuilder*) clearUserId;

- (BOOL) hasLatestUpdateTime;
- (UInt32) latestUpdateTime;
- (IMRecentContactSessionReqBuilder*) setLatestUpdateTime:(UInt32) value;
- (IMRecentContactSessionReqBuilder*) clearLatestUpdateTime;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMRecentContactSessionReqBuilder*) setAttachData:(NSData*) value;
- (IMRecentContactSessionReqBuilder*) clearAttachData;
@end

#define IMRecentContactSessionRsp_user_id @"userId"
#define IMRecentContactSessionRsp_contact_session_list @"contactSessionList"
#define IMRecentContactSessionRsp_attach_data @"attachData"
@interface IMRecentContactSessionRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAttachData_:1;
  BOOL hasUserId_:1;
  NSData* attachData;
  UInt32 userId;
  NSMutableArray * contactSessionListArray;
}
- (BOOL) hasUserId;
- (BOOL) hasAttachData;
@property (readonly) UInt32 userId;
@property (readonly, strong) NSArray * contactSessionList;
@property (readonly, strong) NSData* attachData;
- (ContactSessionInfo*)contactSessionListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMRecentContactSessionRspBuilder*) builder;
+ (IMRecentContactSessionRspBuilder*) builder;
+ (IMRecentContactSessionRspBuilder*) builderWithPrototype:(IMRecentContactSessionRsp*) prototype;
- (IMRecentContactSessionRspBuilder*) toBuilder;

+ (IMRecentContactSessionRsp*) parseFromData:(NSData*) data;
+ (IMRecentContactSessionRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMRecentContactSessionRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMRecentContactSessionRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMRecentContactSessionRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMRecentContactSessionRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMRecentContactSessionRspBuilder : PBGeneratedMessageBuilder {
@private
  IMRecentContactSessionRsp* resultImrecentContactSessionRsp;
}

- (IMRecentContactSessionRsp*) defaultInstance;

- (IMRecentContactSessionRspBuilder*) clear;
- (IMRecentContactSessionRspBuilder*) clone;

- (IMRecentContactSessionRsp*) build;
- (IMRecentContactSessionRsp*) buildPartial;

- (IMRecentContactSessionRspBuilder*) mergeFrom:(IMRecentContactSessionRsp*) other;
- (IMRecentContactSessionRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMRecentContactSessionRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (IMRecentContactSessionRspBuilder*) setUserId:(UInt32) value;
- (IMRecentContactSessionRspBuilder*) clearUserId;

- (NSMutableArray *)contactSessionList;
- (ContactSessionInfo*)contactSessionListAtIndex:(NSUInteger)index;
- (IMRecentContactSessionRspBuilder *)addContactSessionList:(ContactSessionInfo*)value;
- (IMRecentContactSessionRspBuilder *)setContactSessionListArray:(NSArray *)array;
- (IMRecentContactSessionRspBuilder *)clearContactSessionList;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMRecentContactSessionRspBuilder*) setAttachData:(NSData*) value;
- (IMRecentContactSessionRspBuilder*) clearAttachData;
@end

#define IMUserStatNotify_user_stat @"userStat"
@interface IMUserStatNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserStat_:1;
  UserStat* userStat;
}
- (BOOL) hasUserStat;
@property (readonly, strong) UserStat* userStat;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMUserStatNotifyBuilder*) builder;
+ (IMUserStatNotifyBuilder*) builder;
+ (IMUserStatNotifyBuilder*) builderWithPrototype:(IMUserStatNotify*) prototype;
- (IMUserStatNotifyBuilder*) toBuilder;

+ (IMUserStatNotify*) parseFromData:(NSData*) data;
+ (IMUserStatNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMUserStatNotify*) parseFromInputStream:(NSInputStream*) input;
+ (IMUserStatNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMUserStatNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMUserStatNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMUserStatNotifyBuilder : PBGeneratedMessageBuilder {
@private
  IMUserStatNotify* resultImuserStatNotify;
}

- (IMUserStatNotify*) defaultInstance;

- (IMUserStatNotifyBuilder*) clear;
- (IMUserStatNotifyBuilder*) clone;

- (IMUserStatNotify*) build;
- (IMUserStatNotify*) buildPartial;

- (IMUserStatNotifyBuilder*) mergeFrom:(IMUserStatNotify*) other;
- (IMUserStatNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMUserStatNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserStat;
- (UserStat*) userStat;
- (IMUserStatNotifyBuilder*) setUserStat:(UserStat*) value;
- (IMUserStatNotifyBuilder*) setUserStatBuilder:(UserStatBuilder*) builderForValue;
- (IMUserStatNotifyBuilder*) mergeUserStat:(UserStat*) value;
- (IMUserStatNotifyBuilder*) clearUserStat;
@end

#define IMUsersInfoReq_user_id @"userId"
#define IMUsersInfoReq_user_id_list @"userIdList"
#define IMUsersInfoReq_attach_data @"attachData"
@interface IMUsersInfoReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAttachData_:1;
  BOOL hasUserId_:1;
  NSData* attachData;
  UInt32 userId;
  PBAppendableArray * userIdListArray;
}
- (BOOL) hasUserId;
- (BOOL) hasAttachData;
@property (readonly) UInt32 userId;
@property (readonly, strong) PBArray * userIdList;
@property (readonly, strong) NSData* attachData;
- (UInt32)userIdListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMUsersInfoReqBuilder*) builder;
+ (IMUsersInfoReqBuilder*) builder;
+ (IMUsersInfoReqBuilder*) builderWithPrototype:(IMUsersInfoReq*) prototype;
- (IMUsersInfoReqBuilder*) toBuilder;

+ (IMUsersInfoReq*) parseFromData:(NSData*) data;
+ (IMUsersInfoReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMUsersInfoReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMUsersInfoReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMUsersInfoReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMUsersInfoReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMUsersInfoReqBuilder : PBGeneratedMessageBuilder {
@private
  IMUsersInfoReq* resultImusersInfoReq;
}

- (IMUsersInfoReq*) defaultInstance;

- (IMUsersInfoReqBuilder*) clear;
- (IMUsersInfoReqBuilder*) clone;

- (IMUsersInfoReq*) build;
- (IMUsersInfoReq*) buildPartial;

- (IMUsersInfoReqBuilder*) mergeFrom:(IMUsersInfoReq*) other;
- (IMUsersInfoReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMUsersInfoReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (IMUsersInfoReqBuilder*) setUserId:(UInt32) value;
- (IMUsersInfoReqBuilder*) clearUserId;

- (PBAppendableArray *)userIdList;
- (UInt32)userIdListAtIndex:(NSUInteger)index;
- (IMUsersInfoReqBuilder *)addUserIdList:(UInt32)value;
- (IMUsersInfoReqBuilder *)setUserIdListArray:(NSArray *)array;
- (IMUsersInfoReqBuilder *)setUserIdListValues:(const UInt32 *)values count:(NSUInteger)count;
- (IMUsersInfoReqBuilder *)clearUserIdList;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMUsersInfoReqBuilder*) setAttachData:(NSData*) value;
- (IMUsersInfoReqBuilder*) clearAttachData;
@end

#define IMUsersInfoRsp_user_id @"userId"
#define IMUsersInfoRsp_user_info_list @"userInfoList"
#define IMUsersInfoRsp_attach_data @"attachData"
@interface IMUsersInfoRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAttachData_:1;
  BOOL hasUserId_:1;
  NSData* attachData;
  UInt32 userId;
  NSMutableArray * userInfoListArray;
}
- (BOOL) hasUserId;
- (BOOL) hasAttachData;
@property (readonly) UInt32 userId;
@property (readonly, strong) NSArray * userInfoList;
@property (readonly, strong) NSData* attachData;
- (UserInfo*)userInfoListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMUsersInfoRspBuilder*) builder;
+ (IMUsersInfoRspBuilder*) builder;
+ (IMUsersInfoRspBuilder*) builderWithPrototype:(IMUsersInfoRsp*) prototype;
- (IMUsersInfoRspBuilder*) toBuilder;

+ (IMUsersInfoRsp*) parseFromData:(NSData*) data;
+ (IMUsersInfoRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMUsersInfoRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMUsersInfoRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMUsersInfoRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMUsersInfoRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMUsersInfoRspBuilder : PBGeneratedMessageBuilder {
@private
  IMUsersInfoRsp* resultImusersInfoRsp;
}

- (IMUsersInfoRsp*) defaultInstance;

- (IMUsersInfoRspBuilder*) clear;
- (IMUsersInfoRspBuilder*) clone;

- (IMUsersInfoRsp*) build;
- (IMUsersInfoRsp*) buildPartial;

- (IMUsersInfoRspBuilder*) mergeFrom:(IMUsersInfoRsp*) other;
- (IMUsersInfoRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMUsersInfoRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (IMUsersInfoRspBuilder*) setUserId:(UInt32) value;
- (IMUsersInfoRspBuilder*) clearUserId;

- (NSMutableArray *)userInfoList;
- (UserInfo*)userInfoListAtIndex:(NSUInteger)index;
- (IMUsersInfoRspBuilder *)addUserInfoList:(UserInfo*)value;
- (IMUsersInfoRspBuilder *)setUserInfoListArray:(NSArray *)array;
- (IMUsersInfoRspBuilder *)clearUserInfoList;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMUsersInfoRspBuilder*) setAttachData:(NSData*) value;
- (IMUsersInfoRspBuilder*) clearAttachData;
@end

#define IMRemoveSessionReq_user_id @"userId"
#define IMRemoveSessionReq_session_type @"sessionType"
#define IMRemoveSessionReq_session_id @"sessionId"
#define IMRemoveSessionReq_attach_data @"attachData"
@interface IMRemoveSessionReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAttachData_:1;
  BOOL hasUserId_:1;
  BOOL hasSessionId_:1;
  BOOL hasSessionType_:1;
  NSData* attachData;
  UInt32 userId;
  UInt32 sessionId;
  SessionType sessionType;
}
- (BOOL) hasUserId;
- (BOOL) hasSessionType;
- (BOOL) hasSessionId;
- (BOOL) hasAttachData;
@property (readonly) UInt32 userId;
@property (readonly) SessionType sessionType;
@property (readonly) UInt32 sessionId;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMRemoveSessionReqBuilder*) builder;
+ (IMRemoveSessionReqBuilder*) builder;
+ (IMRemoveSessionReqBuilder*) builderWithPrototype:(IMRemoveSessionReq*) prototype;
- (IMRemoveSessionReqBuilder*) toBuilder;

+ (IMRemoveSessionReq*) parseFromData:(NSData*) data;
+ (IMRemoveSessionReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMRemoveSessionReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMRemoveSessionReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMRemoveSessionReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMRemoveSessionReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMRemoveSessionReqBuilder : PBGeneratedMessageBuilder {
@private
  IMRemoveSessionReq* resultImremoveSessionReq;
}

- (IMRemoveSessionReq*) defaultInstance;

- (IMRemoveSessionReqBuilder*) clear;
- (IMRemoveSessionReqBuilder*) clone;

- (IMRemoveSessionReq*) build;
- (IMRemoveSessionReq*) buildPartial;

- (IMRemoveSessionReqBuilder*) mergeFrom:(IMRemoveSessionReq*) other;
- (IMRemoveSessionReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMRemoveSessionReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (IMRemoveSessionReqBuilder*) setUserId:(UInt32) value;
- (IMRemoveSessionReqBuilder*) clearUserId;

- (BOOL) hasSessionType;
- (SessionType) sessionType;
- (IMRemoveSessionReqBuilder*) setSessionType:(SessionType) value;
- (IMRemoveSessionReqBuilder*) clearSessionType;

- (BOOL) hasSessionId;
- (UInt32) sessionId;
- (IMRemoveSessionReqBuilder*) setSessionId:(UInt32) value;
- (IMRemoveSessionReqBuilder*) clearSessionId;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMRemoveSessionReqBuilder*) setAttachData:(NSData*) value;
- (IMRemoveSessionReqBuilder*) clearAttachData;
@end

#define IMRemoveSessionRsp_user_id @"userId"
#define IMRemoveSessionRsp_result_code @"resultCode"
#define IMRemoveSessionRsp_session_type @"sessionType"
#define IMRemoveSessionRsp_session_id @"sessionId"
#define IMRemoveSessionRsp_attach_data @"attachData"
@interface IMRemoveSessionRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAttachData_:1;
  BOOL hasUserId_:1;
  BOOL hasResultCode_:1;
  BOOL hasSessionId_:1;
  BOOL hasSessionType_:1;
  NSData* attachData;
  UInt32 userId;
  UInt32 resultCode;
  UInt32 sessionId;
  SessionType sessionType;
}
- (BOOL) hasUserId;
- (BOOL) hasResultCode;
- (BOOL) hasSessionType;
- (BOOL) hasSessionId;
- (BOOL) hasAttachData;
@property (readonly) UInt32 userId;
@property (readonly) UInt32 resultCode;
@property (readonly) SessionType sessionType;
@property (readonly) UInt32 sessionId;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMRemoveSessionRspBuilder*) builder;
+ (IMRemoveSessionRspBuilder*) builder;
+ (IMRemoveSessionRspBuilder*) builderWithPrototype:(IMRemoveSessionRsp*) prototype;
- (IMRemoveSessionRspBuilder*) toBuilder;

+ (IMRemoveSessionRsp*) parseFromData:(NSData*) data;
+ (IMRemoveSessionRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMRemoveSessionRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMRemoveSessionRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMRemoveSessionRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMRemoveSessionRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMRemoveSessionRspBuilder : PBGeneratedMessageBuilder {
@private
  IMRemoveSessionRsp* resultImremoveSessionRsp;
}

- (IMRemoveSessionRsp*) defaultInstance;

- (IMRemoveSessionRspBuilder*) clear;
- (IMRemoveSessionRspBuilder*) clone;

- (IMRemoveSessionRsp*) build;
- (IMRemoveSessionRsp*) buildPartial;

- (IMRemoveSessionRspBuilder*) mergeFrom:(IMRemoveSessionRsp*) other;
- (IMRemoveSessionRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMRemoveSessionRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (IMRemoveSessionRspBuilder*) setUserId:(UInt32) value;
- (IMRemoveSessionRspBuilder*) clearUserId;

- (BOOL) hasResultCode;
- (UInt32) resultCode;
- (IMRemoveSessionRspBuilder*) setResultCode:(UInt32) value;
- (IMRemoveSessionRspBuilder*) clearResultCode;

- (BOOL) hasSessionType;
- (SessionType) sessionType;
- (IMRemoveSessionRspBuilder*) setSessionType:(SessionType) value;
- (IMRemoveSessionRspBuilder*) clearSessionType;

- (BOOL) hasSessionId;
- (UInt32) sessionId;
- (IMRemoveSessionRspBuilder*) setSessionId:(UInt32) value;
- (IMRemoveSessionRspBuilder*) clearSessionId;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMRemoveSessionRspBuilder*) setAttachData:(NSData*) value;
- (IMRemoveSessionRspBuilder*) clearAttachData;
@end

#define IMAllUserReq_user_id @"userId"
#define IMAllUserReq_latest_update_time @"latestUpdateTime"
#define IMAllUserReq_attach_data @"attachData"
@interface IMAllUserReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAttachData_:1;
  BOOL hasUserId_:1;
  BOOL hasLatestUpdateTime_:1;
  NSData* attachData;
  UInt32 userId;
  UInt32 latestUpdateTime;
}
- (BOOL) hasUserId;
- (BOOL) hasLatestUpdateTime;
- (BOOL) hasAttachData;
@property (readonly) UInt32 userId;
@property (readonly) UInt32 latestUpdateTime;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMAllUserReqBuilder*) builder;
+ (IMAllUserReqBuilder*) builder;
+ (IMAllUserReqBuilder*) builderWithPrototype:(IMAllUserReq*) prototype;
- (IMAllUserReqBuilder*) toBuilder;

+ (IMAllUserReq*) parseFromData:(NSData*) data;
+ (IMAllUserReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMAllUserReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMAllUserReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMAllUserReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMAllUserReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMAllUserReqBuilder : PBGeneratedMessageBuilder {
@private
  IMAllUserReq* resultImallUserReq;
}

- (IMAllUserReq*) defaultInstance;

- (IMAllUserReqBuilder*) clear;
- (IMAllUserReqBuilder*) clone;

- (IMAllUserReq*) build;
- (IMAllUserReq*) buildPartial;

- (IMAllUserReqBuilder*) mergeFrom:(IMAllUserReq*) other;
- (IMAllUserReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMAllUserReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (IMAllUserReqBuilder*) setUserId:(UInt32) value;
- (IMAllUserReqBuilder*) clearUserId;

- (BOOL) hasLatestUpdateTime;
- (UInt32) latestUpdateTime;
- (IMAllUserReqBuilder*) setLatestUpdateTime:(UInt32) value;
- (IMAllUserReqBuilder*) clearLatestUpdateTime;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMAllUserReqBuilder*) setAttachData:(NSData*) value;
- (IMAllUserReqBuilder*) clearAttachData;
@end

#define IMAllUserRsp_user_id @"userId"
#define IMAllUserRsp_latest_update_time @"latestUpdateTime"
#define IMAllUserRsp_user_list @"userList"
#define IMAllUserRsp_attach_data @"attachData"
@interface IMAllUserRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAttachData_:1;
  BOOL hasUserId_:1;
  BOOL hasLatestUpdateTime_:1;
  NSData* attachData;
  UInt32 userId;
  UInt32 latestUpdateTime;
  NSMutableArray * userListArray;
}
- (BOOL) hasUserId;
- (BOOL) hasLatestUpdateTime;
- (BOOL) hasAttachData;
@property (readonly) UInt32 userId;
@property (readonly) UInt32 latestUpdateTime;
@property (readonly, strong) NSArray * userList;
@property (readonly, strong) NSData* attachData;
- (UserInfo*)userListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMAllUserRspBuilder*) builder;
+ (IMAllUserRspBuilder*) builder;
+ (IMAllUserRspBuilder*) builderWithPrototype:(IMAllUserRsp*) prototype;
- (IMAllUserRspBuilder*) toBuilder;

+ (IMAllUserRsp*) parseFromData:(NSData*) data;
+ (IMAllUserRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMAllUserRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMAllUserRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMAllUserRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMAllUserRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMAllUserRspBuilder : PBGeneratedMessageBuilder {
@private
  IMAllUserRsp* resultImallUserRsp;
}

- (IMAllUserRsp*) defaultInstance;

- (IMAllUserRspBuilder*) clear;
- (IMAllUserRspBuilder*) clone;

- (IMAllUserRsp*) build;
- (IMAllUserRsp*) buildPartial;

- (IMAllUserRspBuilder*) mergeFrom:(IMAllUserRsp*) other;
- (IMAllUserRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMAllUserRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (IMAllUserRspBuilder*) setUserId:(UInt32) value;
- (IMAllUserRspBuilder*) clearUserId;

- (BOOL) hasLatestUpdateTime;
- (UInt32) latestUpdateTime;
- (IMAllUserRspBuilder*) setLatestUpdateTime:(UInt32) value;
- (IMAllUserRspBuilder*) clearLatestUpdateTime;

- (NSMutableArray *)userList;
- (UserInfo*)userListAtIndex:(NSUInteger)index;
- (IMAllUserRspBuilder *)addUserList:(UserInfo*)value;
- (IMAllUserRspBuilder *)setUserListArray:(NSArray *)array;
- (IMAllUserRspBuilder *)clearUserList;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMAllUserRspBuilder*) setAttachData:(NSData*) value;
- (IMAllUserRspBuilder*) clearAttachData;
@end

#define IMUsersStatReq_user_id @"userId"
#define IMUsersStatReq_user_id_list @"userIdList"
#define IMUsersStatReq_attach_data @"attachData"
@interface IMUsersStatReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAttachData_:1;
  BOOL hasUserId_:1;
  NSData* attachData;
  UInt32 userId;
  PBAppendableArray * userIdListArray;
}
- (BOOL) hasUserId;
- (BOOL) hasAttachData;
@property (readonly) UInt32 userId;
@property (readonly, strong) PBArray * userIdList;
@property (readonly, strong) NSData* attachData;
- (UInt32)userIdListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMUsersStatReqBuilder*) builder;
+ (IMUsersStatReqBuilder*) builder;
+ (IMUsersStatReqBuilder*) builderWithPrototype:(IMUsersStatReq*) prototype;
- (IMUsersStatReqBuilder*) toBuilder;

+ (IMUsersStatReq*) parseFromData:(NSData*) data;
+ (IMUsersStatReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMUsersStatReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMUsersStatReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMUsersStatReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMUsersStatReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMUsersStatReqBuilder : PBGeneratedMessageBuilder {
@private
  IMUsersStatReq* resultImusersStatReq;
}

- (IMUsersStatReq*) defaultInstance;

- (IMUsersStatReqBuilder*) clear;
- (IMUsersStatReqBuilder*) clone;

- (IMUsersStatReq*) build;
- (IMUsersStatReq*) buildPartial;

- (IMUsersStatReqBuilder*) mergeFrom:(IMUsersStatReq*) other;
- (IMUsersStatReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMUsersStatReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (IMUsersStatReqBuilder*) setUserId:(UInt32) value;
- (IMUsersStatReqBuilder*) clearUserId;

- (PBAppendableArray *)userIdList;
- (UInt32)userIdListAtIndex:(NSUInteger)index;
- (IMUsersStatReqBuilder *)addUserIdList:(UInt32)value;
- (IMUsersStatReqBuilder *)setUserIdListArray:(NSArray *)array;
- (IMUsersStatReqBuilder *)setUserIdListValues:(const UInt32 *)values count:(NSUInteger)count;
- (IMUsersStatReqBuilder *)clearUserIdList;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMUsersStatReqBuilder*) setAttachData:(NSData*) value;
- (IMUsersStatReqBuilder*) clearAttachData;
@end

#define IMUsersStatRsp_user_id @"userId"
#define IMUsersStatRsp_user_stat_list @"userStatList"
#define IMUsersStatRsp_attach_data @"attachData"
@interface IMUsersStatRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAttachData_:1;
  BOOL hasUserId_:1;
  NSData* attachData;
  UInt32 userId;
  NSMutableArray * userStatListArray;
}
- (BOOL) hasUserId;
- (BOOL) hasAttachData;
@property (readonly) UInt32 userId;
@property (readonly, strong) NSArray * userStatList;
@property (readonly, strong) NSData* attachData;
- (UserStat*)userStatListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMUsersStatRspBuilder*) builder;
+ (IMUsersStatRspBuilder*) builder;
+ (IMUsersStatRspBuilder*) builderWithPrototype:(IMUsersStatRsp*) prototype;
- (IMUsersStatRspBuilder*) toBuilder;

+ (IMUsersStatRsp*) parseFromData:(NSData*) data;
+ (IMUsersStatRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMUsersStatRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMUsersStatRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMUsersStatRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMUsersStatRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMUsersStatRspBuilder : PBGeneratedMessageBuilder {
@private
  IMUsersStatRsp* resultImusersStatRsp;
}

- (IMUsersStatRsp*) defaultInstance;

- (IMUsersStatRspBuilder*) clear;
- (IMUsersStatRspBuilder*) clone;

- (IMUsersStatRsp*) build;
- (IMUsersStatRsp*) buildPartial;

- (IMUsersStatRspBuilder*) mergeFrom:(IMUsersStatRsp*) other;
- (IMUsersStatRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMUsersStatRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (IMUsersStatRspBuilder*) setUserId:(UInt32) value;
- (IMUsersStatRspBuilder*) clearUserId;

- (NSMutableArray *)userStatList;
- (UserStat*)userStatListAtIndex:(NSUInteger)index;
- (IMUsersStatRspBuilder *)addUserStatList:(UserStat*)value;
- (IMUsersStatRspBuilder *)setUserStatListArray:(NSArray *)array;
- (IMUsersStatRspBuilder *)clearUserStatList;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMUsersStatRspBuilder*) setAttachData:(NSData*) value;
- (IMUsersStatRspBuilder*) clearAttachData;
@end

#define IMChangeAvatarReq_user_id @"userId"
#define IMChangeAvatarReq_avatar_url @"avatarUrl"
#define IMChangeAvatarReq_attach_data @"attachData"
@interface IMChangeAvatarReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAvatarUrl_:1;
  BOOL hasAttachData_:1;
  BOOL hasUserId_:1;
  NSString* avatarUrl;
  NSData* attachData;
  UInt32 userId;
}
- (BOOL) hasUserId;
- (BOOL) hasAvatarUrl;
- (BOOL) hasAttachData;
@property (readonly) UInt32 userId;
@property (readonly, strong) NSString* avatarUrl;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMChangeAvatarReqBuilder*) builder;
+ (IMChangeAvatarReqBuilder*) builder;
+ (IMChangeAvatarReqBuilder*) builderWithPrototype:(IMChangeAvatarReq*) prototype;
- (IMChangeAvatarReqBuilder*) toBuilder;

+ (IMChangeAvatarReq*) parseFromData:(NSData*) data;
+ (IMChangeAvatarReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMChangeAvatarReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMChangeAvatarReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMChangeAvatarReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMChangeAvatarReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMChangeAvatarReqBuilder : PBGeneratedMessageBuilder {
@private
  IMChangeAvatarReq* resultImchangeAvatarReq;
}

- (IMChangeAvatarReq*) defaultInstance;

- (IMChangeAvatarReqBuilder*) clear;
- (IMChangeAvatarReqBuilder*) clone;

- (IMChangeAvatarReq*) build;
- (IMChangeAvatarReq*) buildPartial;

- (IMChangeAvatarReqBuilder*) mergeFrom:(IMChangeAvatarReq*) other;
- (IMChangeAvatarReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMChangeAvatarReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (IMChangeAvatarReqBuilder*) setUserId:(UInt32) value;
- (IMChangeAvatarReqBuilder*) clearUserId;

- (BOOL) hasAvatarUrl;
- (NSString*) avatarUrl;
- (IMChangeAvatarReqBuilder*) setAvatarUrl:(NSString*) value;
- (IMChangeAvatarReqBuilder*) clearAvatarUrl;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMChangeAvatarReqBuilder*) setAttachData:(NSData*) value;
- (IMChangeAvatarReqBuilder*) clearAttachData;
@end

#define IMChangeAvatarRsp_user_id @"userId"
#define IMChangeAvatarRsp_result_code @"resultCode"
#define IMChangeAvatarRsp_attach_data @"attachData"
@interface IMChangeAvatarRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAttachData_:1;
  BOOL hasUserId_:1;
  BOOL hasResultCode_:1;
  NSData* attachData;
  UInt32 userId;
  UInt32 resultCode;
}
- (BOOL) hasUserId;
- (BOOL) hasResultCode;
- (BOOL) hasAttachData;
@property (readonly) UInt32 userId;
@property (readonly) UInt32 resultCode;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMChangeAvatarRspBuilder*) builder;
+ (IMChangeAvatarRspBuilder*) builder;
+ (IMChangeAvatarRspBuilder*) builderWithPrototype:(IMChangeAvatarRsp*) prototype;
- (IMChangeAvatarRspBuilder*) toBuilder;

+ (IMChangeAvatarRsp*) parseFromData:(NSData*) data;
+ (IMChangeAvatarRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMChangeAvatarRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMChangeAvatarRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMChangeAvatarRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMChangeAvatarRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMChangeAvatarRspBuilder : PBGeneratedMessageBuilder {
@private
  IMChangeAvatarRsp* resultImchangeAvatarRsp;
}

- (IMChangeAvatarRsp*) defaultInstance;

- (IMChangeAvatarRspBuilder*) clear;
- (IMChangeAvatarRspBuilder*) clone;

- (IMChangeAvatarRsp*) build;
- (IMChangeAvatarRsp*) buildPartial;

- (IMChangeAvatarRspBuilder*) mergeFrom:(IMChangeAvatarRsp*) other;
- (IMChangeAvatarRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMChangeAvatarRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (IMChangeAvatarRspBuilder*) setUserId:(UInt32) value;
- (IMChangeAvatarRspBuilder*) clearUserId;

- (BOOL) hasResultCode;
- (UInt32) resultCode;
- (IMChangeAvatarRspBuilder*) setResultCode:(UInt32) value;
- (IMChangeAvatarRspBuilder*) clearResultCode;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMChangeAvatarRspBuilder*) setAttachData:(NSData*) value;
- (IMChangeAvatarRspBuilder*) clearAttachData;
@end

#define IMPCLoginStatusNotify_user_id @"userId"
#define IMPCLoginStatusNotify_login_stat @"loginStat"
@interface IMPCLoginStatusNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasLoginStat_:1;
  UInt32 userId;
  UserStatType loginStat;
}
- (BOOL) hasUserId;
- (BOOL) hasLoginStat;
@property (readonly) UInt32 userId;
@property (readonly) UserStatType loginStat;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMPCLoginStatusNotifyBuilder*) builder;
+ (IMPCLoginStatusNotifyBuilder*) builder;
+ (IMPCLoginStatusNotifyBuilder*) builderWithPrototype:(IMPCLoginStatusNotify*) prototype;
- (IMPCLoginStatusNotifyBuilder*) toBuilder;

+ (IMPCLoginStatusNotify*) parseFromData:(NSData*) data;
+ (IMPCLoginStatusNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMPCLoginStatusNotify*) parseFromInputStream:(NSInputStream*) input;
+ (IMPCLoginStatusNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMPCLoginStatusNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMPCLoginStatusNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMPCLoginStatusNotifyBuilder : PBGeneratedMessageBuilder {
@private
  IMPCLoginStatusNotify* resultImpcloginStatusNotify;
}

- (IMPCLoginStatusNotify*) defaultInstance;

- (IMPCLoginStatusNotifyBuilder*) clear;
- (IMPCLoginStatusNotifyBuilder*) clone;

- (IMPCLoginStatusNotify*) build;
- (IMPCLoginStatusNotify*) buildPartial;

- (IMPCLoginStatusNotifyBuilder*) mergeFrom:(IMPCLoginStatusNotify*) other;
- (IMPCLoginStatusNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMPCLoginStatusNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (IMPCLoginStatusNotifyBuilder*) setUserId:(UInt32) value;
- (IMPCLoginStatusNotifyBuilder*) clearUserId;

- (BOOL) hasLoginStat;
- (UserStatType) loginStat;
- (IMPCLoginStatusNotifyBuilder*) setLoginStat:(UserStatType) value;
- (IMPCLoginStatusNotifyBuilder*) clearLoginStat;
@end

#define IMRemoveSessionNotify_user_id @"userId"
#define IMRemoveSessionNotify_session_type @"sessionType"
#define IMRemoveSessionNotify_session_id @"sessionId"
@interface IMRemoveSessionNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasSessionId_:1;
  BOOL hasSessionType_:1;
  UInt32 userId;
  UInt32 sessionId;
  SessionType sessionType;
}
- (BOOL) hasUserId;
- (BOOL) hasSessionType;
- (BOOL) hasSessionId;
@property (readonly) UInt32 userId;
@property (readonly) SessionType sessionType;
@property (readonly) UInt32 sessionId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMRemoveSessionNotifyBuilder*) builder;
+ (IMRemoveSessionNotifyBuilder*) builder;
+ (IMRemoveSessionNotifyBuilder*) builderWithPrototype:(IMRemoveSessionNotify*) prototype;
- (IMRemoveSessionNotifyBuilder*) toBuilder;

+ (IMRemoveSessionNotify*) parseFromData:(NSData*) data;
+ (IMRemoveSessionNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMRemoveSessionNotify*) parseFromInputStream:(NSInputStream*) input;
+ (IMRemoveSessionNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMRemoveSessionNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMRemoveSessionNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMRemoveSessionNotifyBuilder : PBGeneratedMessageBuilder {
@private
  IMRemoveSessionNotify* resultImremoveSessionNotify;
}

- (IMRemoveSessionNotify*) defaultInstance;

- (IMRemoveSessionNotifyBuilder*) clear;
- (IMRemoveSessionNotifyBuilder*) clone;

- (IMRemoveSessionNotify*) build;
- (IMRemoveSessionNotify*) buildPartial;

- (IMRemoveSessionNotifyBuilder*) mergeFrom:(IMRemoveSessionNotify*) other;
- (IMRemoveSessionNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMRemoveSessionNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (IMRemoveSessionNotifyBuilder*) setUserId:(UInt32) value;
- (IMRemoveSessionNotifyBuilder*) clearUserId;

- (BOOL) hasSessionType;
- (SessionType) sessionType;
- (IMRemoveSessionNotifyBuilder*) setSessionType:(SessionType) value;
- (IMRemoveSessionNotifyBuilder*) clearSessionType;

- (BOOL) hasSessionId;
- (UInt32) sessionId;
- (IMRemoveSessionNotifyBuilder*) setSessionId:(UInt32) value;
- (IMRemoveSessionNotifyBuilder*) clearSessionId;
@end

#define IMDepartmentReq_user_id @"userId"
#define IMDepartmentReq_latest_update_time @"latestUpdateTime"
#define IMDepartmentReq_attach_data @"attachData"
@interface IMDepartmentReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAttachData_:1;
  BOOL hasUserId_:1;
  BOOL hasLatestUpdateTime_:1;
  NSData* attachData;
  UInt32 userId;
  UInt32 latestUpdateTime;
}
- (BOOL) hasUserId;
- (BOOL) hasLatestUpdateTime;
- (BOOL) hasAttachData;
@property (readonly) UInt32 userId;
@property (readonly) UInt32 latestUpdateTime;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMDepartmentReqBuilder*) builder;
+ (IMDepartmentReqBuilder*) builder;
+ (IMDepartmentReqBuilder*) builderWithPrototype:(IMDepartmentReq*) prototype;
- (IMDepartmentReqBuilder*) toBuilder;

+ (IMDepartmentReq*) parseFromData:(NSData*) data;
+ (IMDepartmentReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMDepartmentReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMDepartmentReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMDepartmentReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMDepartmentReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMDepartmentReqBuilder : PBGeneratedMessageBuilder {
@private
  IMDepartmentReq* resultImdepartmentReq;
}

- (IMDepartmentReq*) defaultInstance;

- (IMDepartmentReqBuilder*) clear;
- (IMDepartmentReqBuilder*) clone;

- (IMDepartmentReq*) build;
- (IMDepartmentReq*) buildPartial;

- (IMDepartmentReqBuilder*) mergeFrom:(IMDepartmentReq*) other;
- (IMDepartmentReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMDepartmentReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (IMDepartmentReqBuilder*) setUserId:(UInt32) value;
- (IMDepartmentReqBuilder*) clearUserId;

- (BOOL) hasLatestUpdateTime;
- (UInt32) latestUpdateTime;
- (IMDepartmentReqBuilder*) setLatestUpdateTime:(UInt32) value;
- (IMDepartmentReqBuilder*) clearLatestUpdateTime;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMDepartmentReqBuilder*) setAttachData:(NSData*) value;
- (IMDepartmentReqBuilder*) clearAttachData;
@end

#define IMDepartmentRsp_user_id @"userId"
#define IMDepartmentRsp_latest_update_time @"latestUpdateTime"
#define IMDepartmentRsp_dept_list @"deptList"
#define IMDepartmentRsp_attach_data @"attachData"
@interface IMDepartmentRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAttachData_:1;
  BOOL hasUserId_:1;
  BOOL hasLatestUpdateTime_:1;
  NSData* attachData;
  UInt32 userId;
  UInt32 latestUpdateTime;
  NSMutableArray * deptListArray;
}
- (BOOL) hasUserId;
- (BOOL) hasLatestUpdateTime;
- (BOOL) hasAttachData;
@property (readonly) UInt32 userId;
@property (readonly) UInt32 latestUpdateTime;
@property (readonly, strong) NSArray * deptList;
@property (readonly, strong) NSData* attachData;
- (DepartInfo*)deptListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMDepartmentRspBuilder*) builder;
+ (IMDepartmentRspBuilder*) builder;
+ (IMDepartmentRspBuilder*) builderWithPrototype:(IMDepartmentRsp*) prototype;
- (IMDepartmentRspBuilder*) toBuilder;

+ (IMDepartmentRsp*) parseFromData:(NSData*) data;
+ (IMDepartmentRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMDepartmentRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMDepartmentRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMDepartmentRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMDepartmentRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMDepartmentRspBuilder : PBGeneratedMessageBuilder {
@private
  IMDepartmentRsp* resultImdepartmentRsp;
}

- (IMDepartmentRsp*) defaultInstance;

- (IMDepartmentRspBuilder*) clear;
- (IMDepartmentRspBuilder*) clone;

- (IMDepartmentRsp*) build;
- (IMDepartmentRsp*) buildPartial;

- (IMDepartmentRspBuilder*) mergeFrom:(IMDepartmentRsp*) other;
- (IMDepartmentRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMDepartmentRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (IMDepartmentRspBuilder*) setUserId:(UInt32) value;
- (IMDepartmentRspBuilder*) clearUserId;

- (BOOL) hasLatestUpdateTime;
- (UInt32) latestUpdateTime;
- (IMDepartmentRspBuilder*) setLatestUpdateTime:(UInt32) value;
- (IMDepartmentRspBuilder*) clearLatestUpdateTime;

- (NSMutableArray *)deptList;
- (DepartInfo*)deptListAtIndex:(NSUInteger)index;
- (IMDepartmentRspBuilder *)addDeptList:(DepartInfo*)value;
- (IMDepartmentRspBuilder *)setDeptListArray:(NSArray *)array;
- (IMDepartmentRspBuilder *)clearDeptList;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMDepartmentRspBuilder*) setAttachData:(NSData*) value;
- (IMDepartmentRspBuilder*) clearAttachData;
@end

#define IMAvatarChangedNotify_changed_user_id @"changedUserId"
#define IMAvatarChangedNotify_avatar_url @"avatarUrl"
@interface IMAvatarChangedNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAvatarUrl_:1;
  BOOL hasChangedUserId_:1;
  NSString* avatarUrl;
  UInt32 changedUserId;
}
- (BOOL) hasChangedUserId;
- (BOOL) hasAvatarUrl;
@property (readonly) UInt32 changedUserId;
@property (readonly, strong) NSString* avatarUrl;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMAvatarChangedNotifyBuilder*) builder;
+ (IMAvatarChangedNotifyBuilder*) builder;
+ (IMAvatarChangedNotifyBuilder*) builderWithPrototype:(IMAvatarChangedNotify*) prototype;
- (IMAvatarChangedNotifyBuilder*) toBuilder;

+ (IMAvatarChangedNotify*) parseFromData:(NSData*) data;
+ (IMAvatarChangedNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMAvatarChangedNotify*) parseFromInputStream:(NSInputStream*) input;
+ (IMAvatarChangedNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMAvatarChangedNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMAvatarChangedNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMAvatarChangedNotifyBuilder : PBGeneratedMessageBuilder {
@private
  IMAvatarChangedNotify* resultImavatarChangedNotify;
}

- (IMAvatarChangedNotify*) defaultInstance;

- (IMAvatarChangedNotifyBuilder*) clear;
- (IMAvatarChangedNotifyBuilder*) clone;

- (IMAvatarChangedNotify*) build;
- (IMAvatarChangedNotify*) buildPartial;

- (IMAvatarChangedNotifyBuilder*) mergeFrom:(IMAvatarChangedNotify*) other;
- (IMAvatarChangedNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMAvatarChangedNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChangedUserId;
- (UInt32) changedUserId;
- (IMAvatarChangedNotifyBuilder*) setChangedUserId:(UInt32) value;
- (IMAvatarChangedNotifyBuilder*) clearChangedUserId;

- (BOOL) hasAvatarUrl;
- (NSString*) avatarUrl;
- (IMAvatarChangedNotifyBuilder*) setAvatarUrl:(NSString*) value;
- (IMAvatarChangedNotifyBuilder*) clearAvatarUrl;
@end

#define IMChangeSignInfoReq_user_id @"userId"
#define IMChangeSignInfoReq_sign_info @"signInfo"
#define IMChangeSignInfoReq_attach_data @"attachData"
@interface IMChangeSignInfoReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSignInfo_:1;
  BOOL hasAttachData_:1;
  BOOL hasUserId_:1;
  NSString* signInfo;
  NSData* attachData;
  UInt32 userId;
}
- (BOOL) hasUserId;
- (BOOL) hasSignInfo;
- (BOOL) hasAttachData;
@property (readonly) UInt32 userId;
@property (readonly, strong) NSString* signInfo;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMChangeSignInfoReqBuilder*) builder;
+ (IMChangeSignInfoReqBuilder*) builder;
+ (IMChangeSignInfoReqBuilder*) builderWithPrototype:(IMChangeSignInfoReq*) prototype;
- (IMChangeSignInfoReqBuilder*) toBuilder;

+ (IMChangeSignInfoReq*) parseFromData:(NSData*) data;
+ (IMChangeSignInfoReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMChangeSignInfoReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMChangeSignInfoReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMChangeSignInfoReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMChangeSignInfoReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMChangeSignInfoReqBuilder : PBGeneratedMessageBuilder {
@private
  IMChangeSignInfoReq* resultImchangeSignInfoReq;
}

- (IMChangeSignInfoReq*) defaultInstance;

- (IMChangeSignInfoReqBuilder*) clear;
- (IMChangeSignInfoReqBuilder*) clone;

- (IMChangeSignInfoReq*) build;
- (IMChangeSignInfoReq*) buildPartial;

- (IMChangeSignInfoReqBuilder*) mergeFrom:(IMChangeSignInfoReq*) other;
- (IMChangeSignInfoReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMChangeSignInfoReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (IMChangeSignInfoReqBuilder*) setUserId:(UInt32) value;
- (IMChangeSignInfoReqBuilder*) clearUserId;

- (BOOL) hasSignInfo;
- (NSString*) signInfo;
- (IMChangeSignInfoReqBuilder*) setSignInfo:(NSString*) value;
- (IMChangeSignInfoReqBuilder*) clearSignInfo;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMChangeSignInfoReqBuilder*) setAttachData:(NSData*) value;
- (IMChangeSignInfoReqBuilder*) clearAttachData;
@end

#define IMChangeSignInfoRsp_user_id @"userId"
#define IMChangeSignInfoRsp_result_code @"resultCode"
#define IMChangeSignInfoRsp_sign_info @"signInfo"
#define IMChangeSignInfoRsp_attach_data @"attachData"
@interface IMChangeSignInfoRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSignInfo_:1;
  BOOL hasAttachData_:1;
  BOOL hasUserId_:1;
  BOOL hasResultCode_:1;
  NSString* signInfo;
  NSData* attachData;
  UInt32 userId;
  UInt32 resultCode;
}
- (BOOL) hasUserId;
- (BOOL) hasResultCode;
- (BOOL) hasSignInfo;
- (BOOL) hasAttachData;
@property (readonly) UInt32 userId;
@property (readonly) UInt32 resultCode;
@property (readonly, strong) NSString* signInfo;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMChangeSignInfoRspBuilder*) builder;
+ (IMChangeSignInfoRspBuilder*) builder;
+ (IMChangeSignInfoRspBuilder*) builderWithPrototype:(IMChangeSignInfoRsp*) prototype;
- (IMChangeSignInfoRspBuilder*) toBuilder;

+ (IMChangeSignInfoRsp*) parseFromData:(NSData*) data;
+ (IMChangeSignInfoRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMChangeSignInfoRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMChangeSignInfoRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMChangeSignInfoRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMChangeSignInfoRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMChangeSignInfoRspBuilder : PBGeneratedMessageBuilder {
@private
  IMChangeSignInfoRsp* resultImchangeSignInfoRsp;
}

- (IMChangeSignInfoRsp*) defaultInstance;

- (IMChangeSignInfoRspBuilder*) clear;
- (IMChangeSignInfoRspBuilder*) clone;

- (IMChangeSignInfoRsp*) build;
- (IMChangeSignInfoRsp*) buildPartial;

- (IMChangeSignInfoRspBuilder*) mergeFrom:(IMChangeSignInfoRsp*) other;
- (IMChangeSignInfoRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMChangeSignInfoRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (IMChangeSignInfoRspBuilder*) setUserId:(UInt32) value;
- (IMChangeSignInfoRspBuilder*) clearUserId;

- (BOOL) hasResultCode;
- (UInt32) resultCode;
- (IMChangeSignInfoRspBuilder*) setResultCode:(UInt32) value;
- (IMChangeSignInfoRspBuilder*) clearResultCode;

- (BOOL) hasSignInfo;
- (NSString*) signInfo;
- (IMChangeSignInfoRspBuilder*) setSignInfo:(NSString*) value;
- (IMChangeSignInfoRspBuilder*) clearSignInfo;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMChangeSignInfoRspBuilder*) setAttachData:(NSData*) value;
- (IMChangeSignInfoRspBuilder*) clearAttachData;
@end

#define IMSignInfoChangedNotify_changed_user_id @"changedUserId"
#define IMSignInfoChangedNotify_sign_info @"signInfo"
@interface IMSignInfoChangedNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSignInfo_:1;
  BOOL hasChangedUserId_:1;
  NSString* signInfo;
  UInt32 changedUserId;
}
- (BOOL) hasChangedUserId;
- (BOOL) hasSignInfo;
@property (readonly) UInt32 changedUserId;
@property (readonly, strong) NSString* signInfo;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMSignInfoChangedNotifyBuilder*) builder;
+ (IMSignInfoChangedNotifyBuilder*) builder;
+ (IMSignInfoChangedNotifyBuilder*) builderWithPrototype:(IMSignInfoChangedNotify*) prototype;
- (IMSignInfoChangedNotifyBuilder*) toBuilder;

+ (IMSignInfoChangedNotify*) parseFromData:(NSData*) data;
+ (IMSignInfoChangedNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMSignInfoChangedNotify*) parseFromInputStream:(NSInputStream*) input;
+ (IMSignInfoChangedNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMSignInfoChangedNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMSignInfoChangedNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMSignInfoChangedNotifyBuilder : PBGeneratedMessageBuilder {
@private
  IMSignInfoChangedNotify* resultImsignInfoChangedNotify;
}

- (IMSignInfoChangedNotify*) defaultInstance;

- (IMSignInfoChangedNotifyBuilder*) clear;
- (IMSignInfoChangedNotifyBuilder*) clone;

- (IMSignInfoChangedNotify*) build;
- (IMSignInfoChangedNotify*) buildPartial;

- (IMSignInfoChangedNotifyBuilder*) mergeFrom:(IMSignInfoChangedNotify*) other;
- (IMSignInfoChangedNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMSignInfoChangedNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChangedUserId;
- (UInt32) changedUserId;
- (IMSignInfoChangedNotifyBuilder*) setChangedUserId:(UInt32) value;
- (IMSignInfoChangedNotifyBuilder*) clearChangedUserId;

- (BOOL) hasSignInfo;
- (NSString*) signInfo;
- (IMSignInfoChangedNotifyBuilder*) setSignInfo:(NSString*) value;
- (IMSignInfoChangedNotifyBuilder*) clearSignInfo;
@end


// @@protoc_insertion_point(global_scope)
