// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "IMBaseDefine.pb.h"
// @@protoc_insertion_point(imports)

@class ContactSessionInfo;
@class ContactSessionInfoBuilder;
@class DepartInfo;
@class DepartInfoBuilder;
@class GroupInfo;
@class GroupInfoBuilder;
@class GroupVersionInfo;
@class GroupVersionInfoBuilder;
@class IMFileServerIPReq;
@class IMFileServerIPReqBuilder;
@class IMFileServerIPRsp;
@class IMFileServerIPRspBuilder;
@class IMFileTransferReq;
@class IMFileTransferReqBuilder;
@class IMFileTransferRsp;
@class IMFileTransferRspBuilder;
@class IMGetDeviceTokenReq;
@class IMGetDeviceTokenReqBuilder;
@class IMGetDeviceTokenRsp;
@class IMGetDeviceTokenRspBuilder;
@class IMGroupGetShieldReq;
@class IMGroupGetShieldReqBuilder;
@class IMGroupGetShieldRsp;
@class IMGroupGetShieldRspBuilder;
@class IMMsgServInfo;
@class IMMsgServInfoBuilder;
@class IMOnlineUserInfo;
@class IMOnlineUserInfoBuilder;
@class IMPushToUserReq;
@class IMPushToUserReqBuilder;
@class IMPushToUserRsp;
@class IMPushToUserRspBuilder;
@class IMRoleSet;
@class IMRoleSetBuilder;
@class IMServerKickUser;
@class IMServerKickUserBuilder;
@class IMServerPCLoginStatusNotify;
@class IMServerPCLoginStatusNotifyBuilder;
@class IMStopReceivePacket;
@class IMStopReceivePacketBuilder;
@class IMUserCntUpdate;
@class IMUserCntUpdateBuilder;
@class IMUserStatusUpdate;
@class IMUserStatusUpdateBuilder;
@class IMValidateReq;
@class IMValidateReqBuilder;
@class IMValidateRsp;
@class IMValidateRspBuilder;
@class IpAddr;
@class IpAddrBuilder;
@class MsgInfo;
@class MsgInfoBuilder;
@class OfflineFileInfo;
@class OfflineFileInfoBuilder;
@class PushResult;
@class PushResultBuilder;
@class PushShieldStatus;
@class PushShieldStatusBuilder;
@class ServerUserStat;
@class ServerUserStatBuilder;
@class ShieldStatus;
@class ShieldStatusBuilder;
@class UnreadInfo;
@class UnreadInfoBuilder;
@class UserInfo;
@class UserInfoBuilder;
@class UserStat;
@class UserStatBuilder;
@class UserTokenInfo;
@class UserTokenInfoBuilder;



@interface ImserverRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define IMStopReceivePacket_result @"result"
@interface IMStopReceivePacket : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasResult_:1;
  UInt32 result;
}
- (BOOL) hasResult;
@property (readonly) UInt32 result;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMStopReceivePacketBuilder*) builder;
+ (IMStopReceivePacketBuilder*) builder;
+ (IMStopReceivePacketBuilder*) builderWithPrototype:(IMStopReceivePacket*) prototype;
- (IMStopReceivePacketBuilder*) toBuilder;

+ (IMStopReceivePacket*) parseFromData:(NSData*) data;
+ (IMStopReceivePacket*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMStopReceivePacket*) parseFromInputStream:(NSInputStream*) input;
+ (IMStopReceivePacket*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMStopReceivePacket*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMStopReceivePacket*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMStopReceivePacketBuilder : PBGeneratedMessageBuilder {
@private
  IMStopReceivePacket* resultImstopReceivePacket;
}

- (IMStopReceivePacket*) defaultInstance;

- (IMStopReceivePacketBuilder*) clear;
- (IMStopReceivePacketBuilder*) clone;

- (IMStopReceivePacket*) build;
- (IMStopReceivePacket*) buildPartial;

- (IMStopReceivePacketBuilder*) mergeFrom:(IMStopReceivePacket*) other;
- (IMStopReceivePacketBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMStopReceivePacketBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasResult;
- (UInt32) result;
- (IMStopReceivePacketBuilder*) setResult:(UInt32) value;
- (IMStopReceivePacketBuilder*) clearResult;
@end

#define IMValidateReq_user_name @"userName"
#define IMValidateReq_password @"password"
#define IMValidateReq_attach_data @"attachData"
@interface IMValidateReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserName_:1;
  BOOL hasPassword_:1;
  BOOL hasAttachData_:1;
  NSString* userName;
  NSString* password;
  NSData* attachData;
}
- (BOOL) hasUserName;
- (BOOL) hasPassword;
- (BOOL) hasAttachData;
@property (readonly, strong) NSString* userName;
@property (readonly, strong) NSString* password;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMValidateReqBuilder*) builder;
+ (IMValidateReqBuilder*) builder;
+ (IMValidateReqBuilder*) builderWithPrototype:(IMValidateReq*) prototype;
- (IMValidateReqBuilder*) toBuilder;

+ (IMValidateReq*) parseFromData:(NSData*) data;
+ (IMValidateReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMValidateReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMValidateReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMValidateReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMValidateReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMValidateReqBuilder : PBGeneratedMessageBuilder {
@private
  IMValidateReq* resultImvalidateReq;
}

- (IMValidateReq*) defaultInstance;

- (IMValidateReqBuilder*) clear;
- (IMValidateReqBuilder*) clone;

- (IMValidateReq*) build;
- (IMValidateReq*) buildPartial;

- (IMValidateReqBuilder*) mergeFrom:(IMValidateReq*) other;
- (IMValidateReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMValidateReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserName;
- (NSString*) userName;
- (IMValidateReqBuilder*) setUserName:(NSString*) value;
- (IMValidateReqBuilder*) clearUserName;

- (BOOL) hasPassword;
- (NSString*) password;
- (IMValidateReqBuilder*) setPassword:(NSString*) value;
- (IMValidateReqBuilder*) clearPassword;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMValidateReqBuilder*) setAttachData:(NSData*) value;
- (IMValidateReqBuilder*) clearAttachData;
@end

#define IMValidateRsp_user_name @"userName"
#define IMValidateRsp_result_code @"resultCode"
#define IMValidateRsp_result_string @"resultString"
#define IMValidateRsp_user_info @"userInfo"
#define IMValidateRsp_attach_data @"attachData"
@interface IMValidateRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserName_:1;
  BOOL hasResultString_:1;
  BOOL hasUserInfo_:1;
  BOOL hasAttachData_:1;
  BOOL hasResultCode_:1;
  NSString* userName;
  NSString* resultString;
  UserInfo* userInfo;
  NSData* attachData;
  UInt32 resultCode;
}
- (BOOL) hasUserName;
- (BOOL) hasResultCode;
- (BOOL) hasResultString;
- (BOOL) hasUserInfo;
- (BOOL) hasAttachData;
@property (readonly, strong) NSString* userName;
@property (readonly) UInt32 resultCode;
@property (readonly, strong) NSString* resultString;
@property (readonly, strong) UserInfo* userInfo;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMValidateRspBuilder*) builder;
+ (IMValidateRspBuilder*) builder;
+ (IMValidateRspBuilder*) builderWithPrototype:(IMValidateRsp*) prototype;
- (IMValidateRspBuilder*) toBuilder;

+ (IMValidateRsp*) parseFromData:(NSData*) data;
+ (IMValidateRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMValidateRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMValidateRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMValidateRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMValidateRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMValidateRspBuilder : PBGeneratedMessageBuilder {
@private
  IMValidateRsp* resultImvalidateRsp;
}

- (IMValidateRsp*) defaultInstance;

- (IMValidateRspBuilder*) clear;
- (IMValidateRspBuilder*) clone;

- (IMValidateRsp*) build;
- (IMValidateRsp*) buildPartial;

- (IMValidateRspBuilder*) mergeFrom:(IMValidateRsp*) other;
- (IMValidateRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMValidateRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserName;
- (NSString*) userName;
- (IMValidateRspBuilder*) setUserName:(NSString*) value;
- (IMValidateRspBuilder*) clearUserName;

- (BOOL) hasResultCode;
- (UInt32) resultCode;
- (IMValidateRspBuilder*) setResultCode:(UInt32) value;
- (IMValidateRspBuilder*) clearResultCode;

- (BOOL) hasResultString;
- (NSString*) resultString;
- (IMValidateRspBuilder*) setResultString:(NSString*) value;
- (IMValidateRspBuilder*) clearResultString;

- (BOOL) hasUserInfo;
- (UserInfo*) userInfo;
- (IMValidateRspBuilder*) setUserInfo:(UserInfo*) value;
- (IMValidateRspBuilder*) setUserInfoBuilder:(UserInfoBuilder*) builderForValue;
- (IMValidateRspBuilder*) mergeUserInfo:(UserInfo*) value;
- (IMValidateRspBuilder*) clearUserInfo;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMValidateRspBuilder*) setAttachData:(NSData*) value;
- (IMValidateRspBuilder*) clearAttachData;
@end

#define IMGetDeviceTokenReq_user_id @"userId"
#define IMGetDeviceTokenReq_attach_data @"attachData"
@interface IMGetDeviceTokenReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAttachData_:1;
  NSData* attachData;
  PBAppendableArray * userIdArray;
}
- (BOOL) hasAttachData;
@property (readonly, strong) PBArray * userId;
@property (readonly, strong) NSData* attachData;
- (UInt32)userIdAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGetDeviceTokenReqBuilder*) builder;
+ (IMGetDeviceTokenReqBuilder*) builder;
+ (IMGetDeviceTokenReqBuilder*) builderWithPrototype:(IMGetDeviceTokenReq*) prototype;
- (IMGetDeviceTokenReqBuilder*) toBuilder;

+ (IMGetDeviceTokenReq*) parseFromData:(NSData*) data;
+ (IMGetDeviceTokenReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGetDeviceTokenReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMGetDeviceTokenReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGetDeviceTokenReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGetDeviceTokenReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGetDeviceTokenReqBuilder : PBGeneratedMessageBuilder {
@private
  IMGetDeviceTokenReq* resultImgetDeviceTokenReq;
}

- (IMGetDeviceTokenReq*) defaultInstance;

- (IMGetDeviceTokenReqBuilder*) clear;
- (IMGetDeviceTokenReqBuilder*) clone;

- (IMGetDeviceTokenReq*) build;
- (IMGetDeviceTokenReq*) buildPartial;

- (IMGetDeviceTokenReqBuilder*) mergeFrom:(IMGetDeviceTokenReq*) other;
- (IMGetDeviceTokenReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGetDeviceTokenReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)userId;
- (UInt32)userIdAtIndex:(NSUInteger)index;
- (IMGetDeviceTokenReqBuilder *)addUserId:(UInt32)value;
- (IMGetDeviceTokenReqBuilder *)setUserIdArray:(NSArray *)array;
- (IMGetDeviceTokenReqBuilder *)setUserIdValues:(const UInt32 *)values count:(NSUInteger)count;
- (IMGetDeviceTokenReqBuilder *)clearUserId;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMGetDeviceTokenReqBuilder*) setAttachData:(NSData*) value;
- (IMGetDeviceTokenReqBuilder*) clearAttachData;
@end

#define IMGetDeviceTokenRsp_user_token_info @"userTokenInfo"
#define IMGetDeviceTokenRsp_attach_data @"attachData"
@interface IMGetDeviceTokenRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAttachData_:1;
  NSData* attachData;
  NSMutableArray * userTokenInfoArray;
}
- (BOOL) hasAttachData;
@property (readonly, strong) NSArray * userTokenInfo;
@property (readonly, strong) NSData* attachData;
- (UserTokenInfo*)userTokenInfoAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGetDeviceTokenRspBuilder*) builder;
+ (IMGetDeviceTokenRspBuilder*) builder;
+ (IMGetDeviceTokenRspBuilder*) builderWithPrototype:(IMGetDeviceTokenRsp*) prototype;
- (IMGetDeviceTokenRspBuilder*) toBuilder;

+ (IMGetDeviceTokenRsp*) parseFromData:(NSData*) data;
+ (IMGetDeviceTokenRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGetDeviceTokenRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMGetDeviceTokenRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGetDeviceTokenRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGetDeviceTokenRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGetDeviceTokenRspBuilder : PBGeneratedMessageBuilder {
@private
  IMGetDeviceTokenRsp* resultImgetDeviceTokenRsp;
}

- (IMGetDeviceTokenRsp*) defaultInstance;

- (IMGetDeviceTokenRspBuilder*) clear;
- (IMGetDeviceTokenRspBuilder*) clone;

- (IMGetDeviceTokenRsp*) build;
- (IMGetDeviceTokenRsp*) buildPartial;

- (IMGetDeviceTokenRspBuilder*) mergeFrom:(IMGetDeviceTokenRsp*) other;
- (IMGetDeviceTokenRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGetDeviceTokenRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)userTokenInfo;
- (UserTokenInfo*)userTokenInfoAtIndex:(NSUInteger)index;
- (IMGetDeviceTokenRspBuilder *)addUserTokenInfo:(UserTokenInfo*)value;
- (IMGetDeviceTokenRspBuilder *)setUserTokenInfoArray:(NSArray *)array;
- (IMGetDeviceTokenRspBuilder *)clearUserTokenInfo;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMGetDeviceTokenRspBuilder*) setAttachData:(NSData*) value;
- (IMGetDeviceTokenRspBuilder*) clearAttachData;
@end

#define IMRoleSet_master @"master"
@interface IMRoleSet : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasMaster_:1;
  UInt32 master;
}
- (BOOL) hasMaster;
@property (readonly) UInt32 master;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMRoleSetBuilder*) builder;
+ (IMRoleSetBuilder*) builder;
+ (IMRoleSetBuilder*) builderWithPrototype:(IMRoleSet*) prototype;
- (IMRoleSetBuilder*) toBuilder;

+ (IMRoleSet*) parseFromData:(NSData*) data;
+ (IMRoleSet*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMRoleSet*) parseFromInputStream:(NSInputStream*) input;
+ (IMRoleSet*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMRoleSet*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMRoleSet*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMRoleSetBuilder : PBGeneratedMessageBuilder {
@private
  IMRoleSet* resultImroleSet;
}

- (IMRoleSet*) defaultInstance;

- (IMRoleSetBuilder*) clear;
- (IMRoleSetBuilder*) clone;

- (IMRoleSet*) build;
- (IMRoleSet*) buildPartial;

- (IMRoleSetBuilder*) mergeFrom:(IMRoleSet*) other;
- (IMRoleSetBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMRoleSetBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMaster;
- (UInt32) master;
- (IMRoleSetBuilder*) setMaster:(UInt32) value;
- (IMRoleSetBuilder*) clearMaster;
@end

#define IMOnlineUserInfo_user_stat_list @"userStatList"
@interface IMOnlineUserInfo : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * userStatListArray;
}
@property (readonly, strong) NSArray * userStatList;
- (ServerUserStat*)userStatListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMOnlineUserInfoBuilder*) builder;
+ (IMOnlineUserInfoBuilder*) builder;
+ (IMOnlineUserInfoBuilder*) builderWithPrototype:(IMOnlineUserInfo*) prototype;
- (IMOnlineUserInfoBuilder*) toBuilder;

+ (IMOnlineUserInfo*) parseFromData:(NSData*) data;
+ (IMOnlineUserInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMOnlineUserInfo*) parseFromInputStream:(NSInputStream*) input;
+ (IMOnlineUserInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMOnlineUserInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMOnlineUserInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMOnlineUserInfoBuilder : PBGeneratedMessageBuilder {
@private
  IMOnlineUserInfo* resultImonlineUserInfo;
}

- (IMOnlineUserInfo*) defaultInstance;

- (IMOnlineUserInfoBuilder*) clear;
- (IMOnlineUserInfoBuilder*) clone;

- (IMOnlineUserInfo*) build;
- (IMOnlineUserInfo*) buildPartial;

- (IMOnlineUserInfoBuilder*) mergeFrom:(IMOnlineUserInfo*) other;
- (IMOnlineUserInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMOnlineUserInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)userStatList;
- (ServerUserStat*)userStatListAtIndex:(NSUInteger)index;
- (IMOnlineUserInfoBuilder *)addUserStatList:(ServerUserStat*)value;
- (IMOnlineUserInfoBuilder *)setUserStatListArray:(NSArray *)array;
- (IMOnlineUserInfoBuilder *)clearUserStatList;
@end

#define IMMsgServInfo_ip1 @"ip1"
#define IMMsgServInfo_ip2 @"ip2"
#define IMMsgServInfo_port @"port"
#define IMMsgServInfo_max_conn_cnt @"maxConnCnt"
#define IMMsgServInfo_cur_conn_cnt @"curConnCnt"
#define IMMsgServInfo_host_name @"hostName"
@interface IMMsgServInfo : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasIp1_:1;
  BOOL hasIp2_:1;
  BOOL hasHostName_:1;
  BOOL hasPort_:1;
  BOOL hasMaxConnCnt_:1;
  BOOL hasCurConnCnt_:1;
  NSString* ip1;
  NSString* ip2;
  NSString* hostName;
  UInt32 port;
  UInt32 maxConnCnt;
  UInt32 curConnCnt;
}
- (BOOL) hasIp1;
- (BOOL) hasIp2;
- (BOOL) hasPort;
- (BOOL) hasMaxConnCnt;
- (BOOL) hasCurConnCnt;
- (BOOL) hasHostName;
@property (readonly, strong) NSString* ip1;
@property (readonly, strong) NSString* ip2;
@property (readonly) UInt32 port;
@property (readonly) UInt32 maxConnCnt;
@property (readonly) UInt32 curConnCnt;
@property (readonly, strong) NSString* hostName;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMMsgServInfoBuilder*) builder;
+ (IMMsgServInfoBuilder*) builder;
+ (IMMsgServInfoBuilder*) builderWithPrototype:(IMMsgServInfo*) prototype;
- (IMMsgServInfoBuilder*) toBuilder;

+ (IMMsgServInfo*) parseFromData:(NSData*) data;
+ (IMMsgServInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMMsgServInfo*) parseFromInputStream:(NSInputStream*) input;
+ (IMMsgServInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMMsgServInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMMsgServInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMMsgServInfoBuilder : PBGeneratedMessageBuilder {
@private
  IMMsgServInfo* resultImmsgServInfo;
}

- (IMMsgServInfo*) defaultInstance;

- (IMMsgServInfoBuilder*) clear;
- (IMMsgServInfoBuilder*) clone;

- (IMMsgServInfo*) build;
- (IMMsgServInfo*) buildPartial;

- (IMMsgServInfoBuilder*) mergeFrom:(IMMsgServInfo*) other;
- (IMMsgServInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMMsgServInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIp1;
- (NSString*) ip1;
- (IMMsgServInfoBuilder*) setIp1:(NSString*) value;
- (IMMsgServInfoBuilder*) clearIp1;

- (BOOL) hasIp2;
- (NSString*) ip2;
- (IMMsgServInfoBuilder*) setIp2:(NSString*) value;
- (IMMsgServInfoBuilder*) clearIp2;

- (BOOL) hasPort;
- (UInt32) port;
- (IMMsgServInfoBuilder*) setPort:(UInt32) value;
- (IMMsgServInfoBuilder*) clearPort;

- (BOOL) hasMaxConnCnt;
- (UInt32) maxConnCnt;
- (IMMsgServInfoBuilder*) setMaxConnCnt:(UInt32) value;
- (IMMsgServInfoBuilder*) clearMaxConnCnt;

- (BOOL) hasCurConnCnt;
- (UInt32) curConnCnt;
- (IMMsgServInfoBuilder*) setCurConnCnt:(UInt32) value;
- (IMMsgServInfoBuilder*) clearCurConnCnt;

- (BOOL) hasHostName;
- (NSString*) hostName;
- (IMMsgServInfoBuilder*) setHostName:(NSString*) value;
- (IMMsgServInfoBuilder*) clearHostName;
@end

#define IMUserStatusUpdate_user_status @"userStatus"
#define IMUserStatusUpdate_user_id @"userId"
#define IMUserStatusUpdate_client_type @"clientType"
@interface IMUserStatusUpdate : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserStatus_:1;
  BOOL hasUserId_:1;
  BOOL hasClientType_:1;
  UInt32 userStatus;
  UInt32 userId;
  ClientType clientType;
}
- (BOOL) hasUserStatus;
- (BOOL) hasUserId;
- (BOOL) hasClientType;
@property (readonly) UInt32 userStatus;
@property (readonly) UInt32 userId;
@property (readonly) ClientType clientType;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMUserStatusUpdateBuilder*) builder;
+ (IMUserStatusUpdateBuilder*) builder;
+ (IMUserStatusUpdateBuilder*) builderWithPrototype:(IMUserStatusUpdate*) prototype;
- (IMUserStatusUpdateBuilder*) toBuilder;

+ (IMUserStatusUpdate*) parseFromData:(NSData*) data;
+ (IMUserStatusUpdate*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMUserStatusUpdate*) parseFromInputStream:(NSInputStream*) input;
+ (IMUserStatusUpdate*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMUserStatusUpdate*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMUserStatusUpdate*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMUserStatusUpdateBuilder : PBGeneratedMessageBuilder {
@private
  IMUserStatusUpdate* resultImuserStatusUpdate;
}

- (IMUserStatusUpdate*) defaultInstance;

- (IMUserStatusUpdateBuilder*) clear;
- (IMUserStatusUpdateBuilder*) clone;

- (IMUserStatusUpdate*) build;
- (IMUserStatusUpdate*) buildPartial;

- (IMUserStatusUpdateBuilder*) mergeFrom:(IMUserStatusUpdate*) other;
- (IMUserStatusUpdateBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMUserStatusUpdateBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserStatus;
- (UInt32) userStatus;
- (IMUserStatusUpdateBuilder*) setUserStatus:(UInt32) value;
- (IMUserStatusUpdateBuilder*) clearUserStatus;

- (BOOL) hasUserId;
- (UInt32) userId;
- (IMUserStatusUpdateBuilder*) setUserId:(UInt32) value;
- (IMUserStatusUpdateBuilder*) clearUserId;

- (BOOL) hasClientType;
- (ClientType) clientType;
- (IMUserStatusUpdateBuilder*) setClientType:(ClientType) value;
- (IMUserStatusUpdateBuilder*) clearClientType;
@end

#define IMUserCntUpdate_user_action @"userAction"
#define IMUserCntUpdate_user_id @"userId"
@interface IMUserCntUpdate : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserAction_:1;
  BOOL hasUserId_:1;
  UInt32 userAction;
  UInt32 userId;
}
- (BOOL) hasUserAction;
- (BOOL) hasUserId;
@property (readonly) UInt32 userAction;
@property (readonly) UInt32 userId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMUserCntUpdateBuilder*) builder;
+ (IMUserCntUpdateBuilder*) builder;
+ (IMUserCntUpdateBuilder*) builderWithPrototype:(IMUserCntUpdate*) prototype;
- (IMUserCntUpdateBuilder*) toBuilder;

+ (IMUserCntUpdate*) parseFromData:(NSData*) data;
+ (IMUserCntUpdate*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMUserCntUpdate*) parseFromInputStream:(NSInputStream*) input;
+ (IMUserCntUpdate*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMUserCntUpdate*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMUserCntUpdate*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMUserCntUpdateBuilder : PBGeneratedMessageBuilder {
@private
  IMUserCntUpdate* resultImuserCntUpdate;
}

- (IMUserCntUpdate*) defaultInstance;

- (IMUserCntUpdateBuilder*) clear;
- (IMUserCntUpdateBuilder*) clone;

- (IMUserCntUpdate*) build;
- (IMUserCntUpdate*) buildPartial;

- (IMUserCntUpdateBuilder*) mergeFrom:(IMUserCntUpdate*) other;
- (IMUserCntUpdateBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMUserCntUpdateBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserAction;
- (UInt32) userAction;
- (IMUserCntUpdateBuilder*) setUserAction:(UInt32) value;
- (IMUserCntUpdateBuilder*) clearUserAction;

- (BOOL) hasUserId;
- (UInt32) userId;
- (IMUserCntUpdateBuilder*) setUserId:(UInt32) value;
- (IMUserCntUpdateBuilder*) clearUserId;
@end

#define IMServerKickUser_user_id @"userId"
#define IMServerKickUser_client_type @"clientType"
#define IMServerKickUser_reason @"reason"
@interface IMServerKickUser : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasReason_:1;
  BOOL hasClientType_:1;
  UInt32 userId;
  UInt32 reason;
  ClientType clientType;
}
- (BOOL) hasUserId;
- (BOOL) hasClientType;
- (BOOL) hasReason;
@property (readonly) UInt32 userId;
@property (readonly) ClientType clientType;
@property (readonly) UInt32 reason;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMServerKickUserBuilder*) builder;
+ (IMServerKickUserBuilder*) builder;
+ (IMServerKickUserBuilder*) builderWithPrototype:(IMServerKickUser*) prototype;
- (IMServerKickUserBuilder*) toBuilder;

+ (IMServerKickUser*) parseFromData:(NSData*) data;
+ (IMServerKickUser*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMServerKickUser*) parseFromInputStream:(NSInputStream*) input;
+ (IMServerKickUser*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMServerKickUser*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMServerKickUser*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMServerKickUserBuilder : PBGeneratedMessageBuilder {
@private
  IMServerKickUser* resultImserverKickUser;
}

- (IMServerKickUser*) defaultInstance;

- (IMServerKickUserBuilder*) clear;
- (IMServerKickUserBuilder*) clone;

- (IMServerKickUser*) build;
- (IMServerKickUser*) buildPartial;

- (IMServerKickUserBuilder*) mergeFrom:(IMServerKickUser*) other;
- (IMServerKickUserBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMServerKickUserBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (IMServerKickUserBuilder*) setUserId:(UInt32) value;
- (IMServerKickUserBuilder*) clearUserId;

- (BOOL) hasClientType;
- (ClientType) clientType;
- (IMServerKickUserBuilder*) setClientType:(ClientType) value;
- (IMServerKickUserBuilder*) clearClientType;

- (BOOL) hasReason;
- (UInt32) reason;
- (IMServerKickUserBuilder*) setReason:(UInt32) value;
- (IMServerKickUserBuilder*) clearReason;
@end

#define IMServerPCLoginStatusNotify_user_id @"userId"
#define IMServerPCLoginStatusNotify_login_status @"loginStatus"
@interface IMServerPCLoginStatusNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasLoginStatus_:1;
  UInt32 userId;
  UInt32 loginStatus;
}
- (BOOL) hasUserId;
- (BOOL) hasLoginStatus;
@property (readonly) UInt32 userId;
@property (readonly) UInt32 loginStatus;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMServerPCLoginStatusNotifyBuilder*) builder;
+ (IMServerPCLoginStatusNotifyBuilder*) builder;
+ (IMServerPCLoginStatusNotifyBuilder*) builderWithPrototype:(IMServerPCLoginStatusNotify*) prototype;
- (IMServerPCLoginStatusNotifyBuilder*) toBuilder;

+ (IMServerPCLoginStatusNotify*) parseFromData:(NSData*) data;
+ (IMServerPCLoginStatusNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMServerPCLoginStatusNotify*) parseFromInputStream:(NSInputStream*) input;
+ (IMServerPCLoginStatusNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMServerPCLoginStatusNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMServerPCLoginStatusNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMServerPCLoginStatusNotifyBuilder : PBGeneratedMessageBuilder {
@private
  IMServerPCLoginStatusNotify* resultImserverPcloginStatusNotify;
}

- (IMServerPCLoginStatusNotify*) defaultInstance;

- (IMServerPCLoginStatusNotifyBuilder*) clear;
- (IMServerPCLoginStatusNotifyBuilder*) clone;

- (IMServerPCLoginStatusNotify*) build;
- (IMServerPCLoginStatusNotify*) buildPartial;

- (IMServerPCLoginStatusNotifyBuilder*) mergeFrom:(IMServerPCLoginStatusNotify*) other;
- (IMServerPCLoginStatusNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMServerPCLoginStatusNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt32) userId;
- (IMServerPCLoginStatusNotifyBuilder*) setUserId:(UInt32) value;
- (IMServerPCLoginStatusNotifyBuilder*) clearUserId;

- (BOOL) hasLoginStatus;
- (UInt32) loginStatus;
- (IMServerPCLoginStatusNotifyBuilder*) setLoginStatus:(UInt32) value;
- (IMServerPCLoginStatusNotifyBuilder*) clearLoginStatus;
@end

#define IMPushToUserReq_flash @"flash"
#define IMPushToUserReq_data @"data"
#define IMPushToUserReq_user_token_list @"userTokenList"
@interface IMPushToUserReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasFlash_:1;
  BOOL hasData_:1;
  NSString* flash;
  NSString* data;
  NSMutableArray * userTokenListArray;
}
- (BOOL) hasFlash;
- (BOOL) hasData;
@property (readonly, strong) NSString* flash;
@property (readonly, strong) NSString* data;
@property (readonly, strong) NSArray * userTokenList;
- (UserTokenInfo*)userTokenListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMPushToUserReqBuilder*) builder;
+ (IMPushToUserReqBuilder*) builder;
+ (IMPushToUserReqBuilder*) builderWithPrototype:(IMPushToUserReq*) prototype;
- (IMPushToUserReqBuilder*) toBuilder;

+ (IMPushToUserReq*) parseFromData:(NSData*) data;
+ (IMPushToUserReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMPushToUserReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMPushToUserReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMPushToUserReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMPushToUserReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMPushToUserReqBuilder : PBGeneratedMessageBuilder {
@private
  IMPushToUserReq* resultImpushToUserReq;
}

- (IMPushToUserReq*) defaultInstance;

- (IMPushToUserReqBuilder*) clear;
- (IMPushToUserReqBuilder*) clone;

- (IMPushToUserReq*) build;
- (IMPushToUserReq*) buildPartial;

- (IMPushToUserReqBuilder*) mergeFrom:(IMPushToUserReq*) other;
- (IMPushToUserReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMPushToUserReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFlash;
- (NSString*) flash;
- (IMPushToUserReqBuilder*) setFlash:(NSString*) value;
- (IMPushToUserReqBuilder*) clearFlash;

- (BOOL) hasData;
- (NSString*) data;
- (IMPushToUserReqBuilder*) setData:(NSString*) value;
- (IMPushToUserReqBuilder*) clearData;

- (NSMutableArray *)userTokenList;
- (UserTokenInfo*)userTokenListAtIndex:(NSUInteger)index;
- (IMPushToUserReqBuilder *)addUserTokenList:(UserTokenInfo*)value;
- (IMPushToUserReqBuilder *)setUserTokenListArray:(NSArray *)array;
- (IMPushToUserReqBuilder *)clearUserTokenList;
@end

#define IMPushToUserRsp_push_result_list @"pushResultList"
@interface IMPushToUserRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * pushResultListArray;
}
@property (readonly, strong) NSArray * pushResultList;
- (PushResult*)pushResultListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMPushToUserRspBuilder*) builder;
+ (IMPushToUserRspBuilder*) builder;
+ (IMPushToUserRspBuilder*) builderWithPrototype:(IMPushToUserRsp*) prototype;
- (IMPushToUserRspBuilder*) toBuilder;

+ (IMPushToUserRsp*) parseFromData:(NSData*) data;
+ (IMPushToUserRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMPushToUserRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMPushToUserRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMPushToUserRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMPushToUserRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMPushToUserRspBuilder : PBGeneratedMessageBuilder {
@private
  IMPushToUserRsp* resultImpushToUserRsp;
}

- (IMPushToUserRsp*) defaultInstance;

- (IMPushToUserRspBuilder*) clear;
- (IMPushToUserRspBuilder*) clone;

- (IMPushToUserRsp*) build;
- (IMPushToUserRsp*) buildPartial;

- (IMPushToUserRspBuilder*) mergeFrom:(IMPushToUserRsp*) other;
- (IMPushToUserRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMPushToUserRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)pushResultList;
- (PushResult*)pushResultListAtIndex:(NSUInteger)index;
- (IMPushToUserRspBuilder *)addPushResultList:(PushResult*)value;
- (IMPushToUserRspBuilder *)setPushResultListArray:(NSArray *)array;
- (IMPushToUserRspBuilder *)clearPushResultList;
@end

#define IMGroupGetShieldReq_group_id @"groupId"
#define IMGroupGetShieldReq_user_id @"userId"
#define IMGroupGetShieldReq_attach_data @"attachData"
@interface IMGroupGetShieldReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAttachData_:1;
  BOOL hasGroupId_:1;
  NSData* attachData;
  UInt32 groupId;
  PBAppendableArray * userIdArray;
}
- (BOOL) hasGroupId;
- (BOOL) hasAttachData;
@property (readonly) UInt32 groupId;
@property (readonly, strong) PBArray * userId;
@property (readonly, strong) NSData* attachData;
- (UInt32)userIdAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGroupGetShieldReqBuilder*) builder;
+ (IMGroupGetShieldReqBuilder*) builder;
+ (IMGroupGetShieldReqBuilder*) builderWithPrototype:(IMGroupGetShieldReq*) prototype;
- (IMGroupGetShieldReqBuilder*) toBuilder;

+ (IMGroupGetShieldReq*) parseFromData:(NSData*) data;
+ (IMGroupGetShieldReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupGetShieldReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMGroupGetShieldReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupGetShieldReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGroupGetShieldReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGroupGetShieldReqBuilder : PBGeneratedMessageBuilder {
@private
  IMGroupGetShieldReq* resultImgroupGetShieldReq;
}

- (IMGroupGetShieldReq*) defaultInstance;

- (IMGroupGetShieldReqBuilder*) clear;
- (IMGroupGetShieldReqBuilder*) clone;

- (IMGroupGetShieldReq*) build;
- (IMGroupGetShieldReq*) buildPartial;

- (IMGroupGetShieldReqBuilder*) mergeFrom:(IMGroupGetShieldReq*) other;
- (IMGroupGetShieldReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGroupGetShieldReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (UInt32) groupId;
- (IMGroupGetShieldReqBuilder*) setGroupId:(UInt32) value;
- (IMGroupGetShieldReqBuilder*) clearGroupId;

- (PBAppendableArray *)userId;
- (UInt32)userIdAtIndex:(NSUInteger)index;
- (IMGroupGetShieldReqBuilder *)addUserId:(UInt32)value;
- (IMGroupGetShieldReqBuilder *)setUserIdArray:(NSArray *)array;
- (IMGroupGetShieldReqBuilder *)setUserIdValues:(const UInt32 *)values count:(NSUInteger)count;
- (IMGroupGetShieldReqBuilder *)clearUserId;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMGroupGetShieldReqBuilder*) setAttachData:(NSData*) value;
- (IMGroupGetShieldReqBuilder*) clearAttachData;
@end

#define IMGroupGetShieldRsp_group_id @"groupId"
#define IMGroupGetShieldRsp_shield_status_list @"shieldStatusList"
#define IMGroupGetShieldRsp_attach_data @"attachData"
@interface IMGroupGetShieldRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAttachData_:1;
  BOOL hasGroupId_:1;
  NSData* attachData;
  UInt32 groupId;
  NSMutableArray * shieldStatusListArray;
}
- (BOOL) hasGroupId;
- (BOOL) hasAttachData;
@property (readonly) UInt32 groupId;
@property (readonly, strong) NSArray * shieldStatusList;
@property (readonly, strong) NSData* attachData;
- (ShieldStatus*)shieldStatusListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGroupGetShieldRspBuilder*) builder;
+ (IMGroupGetShieldRspBuilder*) builder;
+ (IMGroupGetShieldRspBuilder*) builderWithPrototype:(IMGroupGetShieldRsp*) prototype;
- (IMGroupGetShieldRspBuilder*) toBuilder;

+ (IMGroupGetShieldRsp*) parseFromData:(NSData*) data;
+ (IMGroupGetShieldRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupGetShieldRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMGroupGetShieldRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupGetShieldRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGroupGetShieldRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGroupGetShieldRspBuilder : PBGeneratedMessageBuilder {
@private
  IMGroupGetShieldRsp* resultImgroupGetShieldRsp;
}

- (IMGroupGetShieldRsp*) defaultInstance;

- (IMGroupGetShieldRspBuilder*) clear;
- (IMGroupGetShieldRspBuilder*) clone;

- (IMGroupGetShieldRsp*) build;
- (IMGroupGetShieldRsp*) buildPartial;

- (IMGroupGetShieldRspBuilder*) mergeFrom:(IMGroupGetShieldRsp*) other;
- (IMGroupGetShieldRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGroupGetShieldRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (UInt32) groupId;
- (IMGroupGetShieldRspBuilder*) setGroupId:(UInt32) value;
- (IMGroupGetShieldRspBuilder*) clearGroupId;

- (NSMutableArray *)shieldStatusList;
- (ShieldStatus*)shieldStatusListAtIndex:(NSUInteger)index;
- (IMGroupGetShieldRspBuilder *)addShieldStatusList:(ShieldStatus*)value;
- (IMGroupGetShieldRspBuilder *)setShieldStatusListArray:(NSArray *)array;
- (IMGroupGetShieldRspBuilder *)clearShieldStatusList;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMGroupGetShieldRspBuilder*) setAttachData:(NSData*) value;
- (IMGroupGetShieldRspBuilder*) clearAttachData;
@end

#define IMFileTransferReq_from_user_id @"fromUserId"
#define IMFileTransferReq_to_user_id @"toUserId"
#define IMFileTransferReq_file_name @"fileName"
#define IMFileTransferReq_file_size @"fileSize"
#define IMFileTransferReq_trans_mode @"transMode"
#define IMFileTransferReq_attach_data @"attachData"
@interface IMFileTransferReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasFileName_:1;
  BOOL hasAttachData_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  BOOL hasFileSize_:1;
  BOOL hasTransMode_:1;
  NSString* fileName;
  NSData* attachData;
  UInt32 fromUserId;
  UInt32 toUserId;
  UInt32 fileSize;
  TransferFileType transMode;
}
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasFileName;
- (BOOL) hasFileSize;
- (BOOL) hasTransMode;
- (BOOL) hasAttachData;
@property (readonly) UInt32 fromUserId;
@property (readonly) UInt32 toUserId;
@property (readonly, strong) NSString* fileName;
@property (readonly) UInt32 fileSize;
@property (readonly) TransferFileType transMode;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMFileTransferReqBuilder*) builder;
+ (IMFileTransferReqBuilder*) builder;
+ (IMFileTransferReqBuilder*) builderWithPrototype:(IMFileTransferReq*) prototype;
- (IMFileTransferReqBuilder*) toBuilder;

+ (IMFileTransferReq*) parseFromData:(NSData*) data;
+ (IMFileTransferReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileTransferReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMFileTransferReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileTransferReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMFileTransferReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMFileTransferReqBuilder : PBGeneratedMessageBuilder {
@private
  IMFileTransferReq* resultImfileTransferReq;
}

- (IMFileTransferReq*) defaultInstance;

- (IMFileTransferReqBuilder*) clear;
- (IMFileTransferReqBuilder*) clone;

- (IMFileTransferReq*) build;
- (IMFileTransferReq*) buildPartial;

- (IMFileTransferReqBuilder*) mergeFrom:(IMFileTransferReq*) other;
- (IMFileTransferReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMFileTransferReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromUserId;
- (UInt32) fromUserId;
- (IMFileTransferReqBuilder*) setFromUserId:(UInt32) value;
- (IMFileTransferReqBuilder*) clearFromUserId;

- (BOOL) hasToUserId;
- (UInt32) toUserId;
- (IMFileTransferReqBuilder*) setToUserId:(UInt32) value;
- (IMFileTransferReqBuilder*) clearToUserId;

- (BOOL) hasFileName;
- (NSString*) fileName;
- (IMFileTransferReqBuilder*) setFileName:(NSString*) value;
- (IMFileTransferReqBuilder*) clearFileName;

- (BOOL) hasFileSize;
- (UInt32) fileSize;
- (IMFileTransferReqBuilder*) setFileSize:(UInt32) value;
- (IMFileTransferReqBuilder*) clearFileSize;

- (BOOL) hasTransMode;
- (TransferFileType) transMode;
- (IMFileTransferReqBuilder*) setTransMode:(TransferFileType) value;
- (IMFileTransferReqBuilder*) clearTransMode;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMFileTransferReqBuilder*) setAttachData:(NSData*) value;
- (IMFileTransferReqBuilder*) clearAttachData;
@end

#define IMFileTransferRsp_result_code @"resultCode"
#define IMFileTransferRsp_from_user_id @"fromUserId"
#define IMFileTransferRsp_to_user_id @"toUserId"
#define IMFileTransferRsp_file_name @"fileName"
#define IMFileTransferRsp_file_size @"fileSize"
#define IMFileTransferRsp_task_id @"taskId"
#define IMFileTransferRsp_trans_mode @"transMode"
#define IMFileTransferRsp_attach_data @"attachData"
@interface IMFileTransferRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasFileName_:1;
  BOOL hasTaskId_:1;
  BOOL hasAttachData_:1;
  BOOL hasResultCode_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  BOOL hasFileSize_:1;
  BOOL hasTransMode_:1;
  NSString* fileName;
  NSString* taskId;
  NSData* attachData;
  UInt32 resultCode;
  UInt32 fromUserId;
  UInt32 toUserId;
  UInt32 fileSize;
  TransferFileType transMode;
}
- (BOOL) hasResultCode;
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasFileName;
- (BOOL) hasFileSize;
- (BOOL) hasTaskId;
- (BOOL) hasTransMode;
- (BOOL) hasAttachData;
@property (readonly) UInt32 resultCode;
@property (readonly) UInt32 fromUserId;
@property (readonly) UInt32 toUserId;
@property (readonly, strong) NSString* fileName;
@property (readonly) UInt32 fileSize;
@property (readonly, strong) NSString* taskId;
@property (readonly) TransferFileType transMode;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMFileTransferRspBuilder*) builder;
+ (IMFileTransferRspBuilder*) builder;
+ (IMFileTransferRspBuilder*) builderWithPrototype:(IMFileTransferRsp*) prototype;
- (IMFileTransferRspBuilder*) toBuilder;

+ (IMFileTransferRsp*) parseFromData:(NSData*) data;
+ (IMFileTransferRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileTransferRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMFileTransferRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileTransferRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMFileTransferRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMFileTransferRspBuilder : PBGeneratedMessageBuilder {
@private
  IMFileTransferRsp* resultImfileTransferRsp;
}

- (IMFileTransferRsp*) defaultInstance;

- (IMFileTransferRspBuilder*) clear;
- (IMFileTransferRspBuilder*) clone;

- (IMFileTransferRsp*) build;
- (IMFileTransferRsp*) buildPartial;

- (IMFileTransferRspBuilder*) mergeFrom:(IMFileTransferRsp*) other;
- (IMFileTransferRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMFileTransferRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasResultCode;
- (UInt32) resultCode;
- (IMFileTransferRspBuilder*) setResultCode:(UInt32) value;
- (IMFileTransferRspBuilder*) clearResultCode;

- (BOOL) hasFromUserId;
- (UInt32) fromUserId;
- (IMFileTransferRspBuilder*) setFromUserId:(UInt32) value;
- (IMFileTransferRspBuilder*) clearFromUserId;

- (BOOL) hasToUserId;
- (UInt32) toUserId;
- (IMFileTransferRspBuilder*) setToUserId:(UInt32) value;
- (IMFileTransferRspBuilder*) clearToUserId;

- (BOOL) hasFileName;
- (NSString*) fileName;
- (IMFileTransferRspBuilder*) setFileName:(NSString*) value;
- (IMFileTransferRspBuilder*) clearFileName;

- (BOOL) hasFileSize;
- (UInt32) fileSize;
- (IMFileTransferRspBuilder*) setFileSize:(UInt32) value;
- (IMFileTransferRspBuilder*) clearFileSize;

- (BOOL) hasTaskId;
- (NSString*) taskId;
- (IMFileTransferRspBuilder*) setTaskId:(NSString*) value;
- (IMFileTransferRspBuilder*) clearTaskId;

- (BOOL) hasTransMode;
- (TransferFileType) transMode;
- (IMFileTransferRspBuilder*) setTransMode:(TransferFileType) value;
- (IMFileTransferRspBuilder*) clearTransMode;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMFileTransferRspBuilder*) setAttachData:(NSData*) value;
- (IMFileTransferRspBuilder*) clearAttachData;
@end

@interface IMFileServerIPReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMFileServerIPReqBuilder*) builder;
+ (IMFileServerIPReqBuilder*) builder;
+ (IMFileServerIPReqBuilder*) builderWithPrototype:(IMFileServerIPReq*) prototype;
- (IMFileServerIPReqBuilder*) toBuilder;

+ (IMFileServerIPReq*) parseFromData:(NSData*) data;
+ (IMFileServerIPReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileServerIPReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMFileServerIPReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileServerIPReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMFileServerIPReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMFileServerIPReqBuilder : PBGeneratedMessageBuilder {
@private
  IMFileServerIPReq* resultImfileServerIpreq;
}

- (IMFileServerIPReq*) defaultInstance;

- (IMFileServerIPReqBuilder*) clear;
- (IMFileServerIPReqBuilder*) clone;

- (IMFileServerIPReq*) build;
- (IMFileServerIPReq*) buildPartial;

- (IMFileServerIPReqBuilder*) mergeFrom:(IMFileServerIPReq*) other;
- (IMFileServerIPReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMFileServerIPReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define IMFileServerIPRsp_ip_addr_list @"ipAddrList"
@interface IMFileServerIPRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * ipAddrListArray;
}
@property (readonly, strong) NSArray * ipAddrList;
- (IpAddr*)ipAddrListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMFileServerIPRspBuilder*) builder;
+ (IMFileServerIPRspBuilder*) builder;
+ (IMFileServerIPRspBuilder*) builderWithPrototype:(IMFileServerIPRsp*) prototype;
- (IMFileServerIPRspBuilder*) toBuilder;

+ (IMFileServerIPRsp*) parseFromData:(NSData*) data;
+ (IMFileServerIPRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileServerIPRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMFileServerIPRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileServerIPRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMFileServerIPRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMFileServerIPRspBuilder : PBGeneratedMessageBuilder {
@private
  IMFileServerIPRsp* resultImfileServerIprsp;
}

- (IMFileServerIPRsp*) defaultInstance;

- (IMFileServerIPRspBuilder*) clear;
- (IMFileServerIPRspBuilder*) clone;

- (IMFileServerIPRsp*) build;
- (IMFileServerIPRsp*) buildPartial;

- (IMFileServerIPRspBuilder*) mergeFrom:(IMFileServerIPRsp*) other;
- (IMFileServerIPRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMFileServerIPRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)ipAddrList;
- (IpAddr*)ipAddrListAtIndex:(NSUInteger)index;
- (IMFileServerIPRspBuilder *)addIpAddrList:(IpAddr*)value;
- (IMFileServerIPRspBuilder *)setIpAddrListArray:(NSArray *)array;
- (IMFileServerIPRspBuilder *)clearIpAddrList;
@end


// @@protoc_insertion_point(global_scope)
